New Indonesian Translation: Your First Component
reactjs/id.react.dev pull request #338
Opened 2023-04-26 08:16 UTC by Cikang44

Hi, this is a Pull Request for #330
Translation for Describing The UI -> Your First Component.

2023-04-26 08:29 UTC, r17x commented on src/content/learn/your-first-component.md
> +Komponen merupakan salah satu konsep inti dari React. Komponen adalah fondasi di mana anda bangun antarmuka pengguna (UI), yang membuat komponen tempat yang sempurna untuk memulai perjalan React anda
@resir014 Penggunaan kata "anda" apakah kontekstual ataukah lebih baik seragam "Anda". dibeberapa translasi menggunakan "Anda" untuk penyebutan ini.

2023-04-26 08:41 UTC, resir014 requested changes

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Komponen merupakan salah satu konsep inti dari React. Komponen adalah fondasi di mana anda bangun antarmuka pengguna (UI), yang membuat komponen tempat yang sempurna untuk memulai perjalan React anda
Yep. @Cikang44 

```suggestion
Komponen merupakan salah satu konsep inti dari React. Komponen adalah fondasi di mana Anda bangun antarmuka pengguna (UI), yang membuat komponen tempat yang sempurna untuk memulai perjalan React Anda!
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +* Bagaimana cara menulis komponen React pertama anda
```suggestion
* Bagaimana cara menulis komponen React pertama Anda
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +*Markup* ini merepresentasikan artikel `<article>`, heading `<h1>` dan daftar isi (yang disingkat) sebagai daftar yang tersusun `<ol>`. *Markup* seperti ini, digabung dengan CSS untuk *style*, dan *J
```suggestion
*Markup* ini merepresentasikan artikel `<article>`, heading `<h1>` dan daftar isi (yang disingkat) sebagai daftar yang tersusun `<ol>`. *Markup* seperti ini, digabung dengan CSS untuk *style*, dan *Javascript* untuk interaktivitas, berada di belakang setiap *sidebar*, *avatar*, *modal*, *dropdown*—setiap potongan UI yang Anda liat di dalam *web*.
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +React memungkinkan anda menggabung *markup*, CSS, dan *Javascript* anda menjadi "komponen" yang dibuat khusus, **elemen UI yang dapat digunakan kembali untuk aplikasi anda.** Daftar isi yang anda lih
```suggestion
React memungkinkan Anda menggabung *markup*, CSS, dan *Javascript* Anda menjadi "komponen" yang dibuat khusus, **elemen UI yang dapat digunakan kembali untuk aplikasi Anda.** Daftar isi yang Anda lihat di atas dapat diubah menjadi sebuah komponen `<TableOfContents />` yang dapat Anda *render* pada setiap halaman. Dari belakang, itu tetap menggunakan *tag* HTML yang sama seperti `<article>`, `h1`, dll.
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Sama seperti *tag* HTML, anda dapat menggabung, mengurut, dan menyusun bertingkat komponen untuk mendesain halaman penuh. Misalnya, halaman dokumentasi ini yang anda baca terbuat oleh komponen-kompon
```suggestion
Sama seperti *tag* HTML, Anda dapat menggabung, mengurut, dan menyusun bertingkat komponen untuk mendesain halaman penuh. Misalnya, halaman dokumentasi ini yang Anda baca terbuat oleh komponen-komponen React: 
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Seiring berkembangnya proyek anda, anda akan memperhatikan bahwa banyak desain anda bisa dikomposisi dengan menggunakan ulang komponen-komponen yang sudah anda buat, mempercepatkan perkembangan proye
```suggestion
Seiring berkembangnya proyek anda, anda akan memperhatikan bahwa banyak desain anda bisa dikomposisi dengan menggunakan ulang komponen-komponen yang sudah anda buat, mempercepatkan perkembangan proyek anda. Daftar isi kita di atas bisa disertakan pada layar apapun dengan `<TableOfContents />`! Anda bisa memulai proyek Anda dengan cepat menggunakan ribuan komponen-komponen yang dibagi oleh komunitas *open source* React seperti [Chakra UI](https://chakra-ui.com/) dan [Material UI.](https://material-ui.com/)
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Secara tradisional saat menciptakan halaman *web*, para *web developer* me-*mark-up* konten mereka kemudian menambahkan interaksi dengan sedikit *Javascript*. Ini bekerja dengan baik ketika interaksi
```suggestion
Secara tradisional saat menciptakan halaman *web*, para *web developer* me-*mark-up* konten mereka kemudian menambahkan interaksi dengan sedikit *Javascript*. Ini bekerja dengan baik ketika interaksi hanya menyenangkan-untuk-dimiliki di dalam *web*. Sekarang ini diharapkan banyak situs dan semua aplikasi. React mengutamakan interaktivitas dengan tetap menggunakan teknologi yang sama: **Sebuah komponen React adalah sebuah fungsi _Javascript_ yang dapat Anda _tambahkan dengan markup_.** Inilah tampilannya (Anda bisa sunting contoh di bawah ini):
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +awalan `export default` adalah sebuah [sintaksis *Javascript* standar](https://developer.mozilla.org/docs/web/javascript/reference/statements/export) (tidak spesifik kepada React). Itu memungkinkan a
```suggestion
awalan `export default` adalah sebuah [sintaksis *Javascript* standar](https://developer.mozilla.org/docs/web/javascript/reference/statements/export) (tidak spesifik kepada React). Itu memungkinkan Anda menandai fungsi utama di sebuah file supaya anda bisa mengimport itu dari *file-file* lain nantinya. (Lebih lanjut tentang mengimport di [Mengimport dan Mengeksport Komponen](/learn/importing-and-exporting-components)!)
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Dengan `function Profile() { }` anda mendefinisikan fungsi *Javascript* dengan nama `Profile`.
```suggestion
Dengan `function Profile() { }` Anda mendefinisikan fungsi *Javascript* dengan nama `Profile`.
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Komponen itu mengembalikan *tag* `<img />` dengan atribut `src` dan `alt`. `<img />` ditulis seperti HTML, tetapi ini sebenarnya merupakan *Javascript* di belakang! Sintaksis ini disebut [JSX](/learn
```suggestion
Komponen itu mengembalikan *tag* `<img />` dengan atribut `src` dan `alt`. `<img />` ditulis seperti HTML, tetapi ini sebenarnya merupakan *Javascript* di belakang! Sintaksis ini disebut [JSX](/learn/writing-markup-with-jsx), dan ini memungkinkan Anda untuk *embed* *markup* di dalam *Javascript*.
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Tetapi jika *markup* anda tidak semua ada di baris yang sama dengan *keyword* `return`, anda harus membungkus itu dalam tanda kurung:
```suggestion
Tetapi jika *markup* Anda tidak semua ada di baris yang sama dengan *keyword* `return`, Anda harus membungkus itu dalam tanda kurung:
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Sekarang setelah anda mendefinisikan komponen `Profile` anda, anda bisa meletakkan itu di dalam komponen-komponen lain secara bertingkat. Misalnya, anda bisa eksport sebuah komponen `Gallery` yang me
```suggestion
Sekarang setelah anda mendefinisikan komponen `Profile` Anda, Anda bisa meletakkan itu di dalam komponen-komponen lain secara bertingkat. Misalnya, Anda bisa eksport sebuah komponen `Gallery` yang menggunakan beberapa komponen `Profile`:
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Komponen adalah fungsi *Javascript* biasa, sehingga anda bisa menjaga beberapa komponen di dalam *file* yang sama. Ini nyaman ketika komponen-komponen relatif kecil atau saling terkait secara erat. J
```suggestion
Komponen adalah fungsi *Javascript* biasa, sehingga Anda bisa menjaga beberapa komponen di dalam *file* yang sama. Ini nyaman ketika komponen-komponen relatif kecil atau saling terkait secara erat. Jika *file* ini menjadi ramai, Anda selalu bisa memindahkan `Profile` kepada suatu *file* yang beda. Anda akan belajar bagaimana cara melakukan ini segera di [halaman tentang import.](/learn/importing-and-exporting-components)
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Karena komponen-komponen `Profile` di-*render* di dalam `Gallery`—bahkan beberapa kali!—kita dapat mengatakan bahwa `Gallery` adalah sebuah **komponen induk,** yang me-*render* setiap `Profile` sebag
```suggestion
Karena komponen-komponen `Profile` di-*render* di dalam `Gallery`—bahkan beberapa kali!—kita dapat mengatakan bahwa `Gallery` adalah sebuah **komponen induk,** yang me-*render* setiap `Profile` sebagai sebuah "anak". Ini merupakan bagian ajaib dari React: Anda bisa mendefinisikan suatu komponen sekali, kemudian digunakan di banyak tempat dan sebanyak kali yang Anda suka.
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Komponen dapat me-*render* komponen lain, tetapi **anda tidak boleh menyusun definisinya secara bertingkat:**
```suggestion
Komponen dapat me-*render* komponen lain, tetapi **Anda tidak boleh menyusun definisinya secara bertingkat:**
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Aplikasi React anda dimulai dari suatu komponen "*root*". Biasanya, itu dibuat secara otomatis saat anda memulai proyek baru. Misalnya, jika anda menggunakan [CodeSandbox](https://codesandbox.io/) at
```suggestion
Aplikasi React Anda dimulai dari suatu komponen "*root*". Biasanya, itu dibuat secara otomatis saat Anda memulai proyek baru. Misalnya, jika Anda menggunakan [CodeSandbox](https://codesandbox.io/) atau [Create React App](https://create-react-app.dev/), komponen *root* didefinisikan di `src/App.js`. Jika Anda menggunakan *framework* [Next.js](https://nextjs.org/), komponen *root* didefinisikan di `pages/index.js`. Dalam contoh-contoh berikut, Anda telah mengeksport komponen-komponen *root*.
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +[*Framework-framework* berbasis React](/learn/start-a-new-react-project) mengambil ini selangkah lebih jauh. Daripada menggunakan sebuah *file* HTML yang kosong dan membiarkan React untuk "mengambil
```suggestion
[*Framework-framework* berbasis React](/learn/start-a-new-react-project) mengambil ini selangkah lebih jauh. Daripada menggunakan sebuah *file* HTML yang kosong dan membiarkan React untuk "mengambil alih" dalam mengelola halamannya dengan *Javascript*, mereka *juga* membuat HTML-nya secara otomatis dari komponen-komponen React Anda. Ini memungkinkan aplikasi Anda menampilkan beberapa konten sebelum kode *Javascript* dimuat.
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +* React memungkinkan anda untuk membuat komponen, **elemen UI yang dapat digunakan kembali untuk aplikasi anda**
```suggestion
* React memungkinkan Anda untuk membuat komponen, **elemen UI yang dapat digunakan kembali untuk aplikasi Anda**
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Ada yang tidak benar tentang pernyataan `return` ini. Dapatkah anda memperbaikinya?
```suggestion
Ada yang tidak benar tentang pernyataan `return` ini. Dapatkah Anda memperbaikinya?
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Ada yang salah dengan bagaimana komponen `Profile` dideklarasi dan digunakan. Dapatkah anda temukan masalahnya? (Coba untuk mengingat kembali bagaimana React membedakan komponen dengan *tag* HTML bia
```suggestion
Ada yang salah dengan bagaimana komponen `Profile` dideklarasi dan digunakan. Dapatkah Anda temukan masalahnya? (Coba untuk mengingat kembali bagaimana React membedakan komponen dengan *tag* HTML biasa!)
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +#### Komponen anda sendiri {/*your-own-component*/}
```suggestion
#### Komponen Anda sendiri {/*your-own-component*/}
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Tulislah sebuah komponen dari awal. Anda bisa memberikannya nama apapun yang benar dan mengembalikan *markup* apapun. Jika anda kehabisan ide, anda bisa tulis sebuah komponen `Congratuliations` yang
```suggestion
Tulislah sebuah komponen dari awal. Anda bisa memberikannya nama apapun yang benar dan mengembalikan *markup* apapun. Jika Anda kehabisan ide, anda bisa tulis sebuah komponen `Congratulations` yang menampilkan `<h1>Kerja bagus!</h1>`. Jangan lupa untuk dieksport!
```

2023-04-26 08:41 UTC, resir014 commented on src/content/learn/your-first-component.md
> +// Tulislah komponen anda di bawah ini!
```suggestion
// Tulislah komponen Anda di bawah ini!
```

2023-04-26 10:12 UTC, r17x approved these changes

2023-04-27 02:32 UTC, resir014 approved these changes

2023-04-27 02:33 UTC, resir014 commented on src/content/learn/your-first-component.md
> +Anda mungkin mendapatakan sebuah kesalahan "*Unexpected Token*" saat mencoba memperbaiki ini. Dalam hal itu, cek kembali bahwa titik koma muncul *setelah* tanda kurung. Meletakkan suatu titik koma di
```suggestion
Anda mungkin mendapatkan sebuah kesalahan "*Unexpected Token*" saat mencoba memperbaiki ini. Dalam hal itu, cek kembali bahwa titik koma muncul *setelah* tanda kurung. Meletakkan suatu titik koma di dalam `return ( )` akan mengakibatkan sebuah kesalahan.
```

2023-04-27 02:56 UTC, merged