update: translate `useDebugValue`
reactjs/id.react.dev pull request #348
Opened 2023-04-26 16:44 UTC by arganaphang

- update: translate `hooks:useDebugValue` page

2023-04-26 17:35 UTC, r17x commented on src/content/reference/react/useDebugValue.md
> +Panggil `useDebugValue` di bagian atas [kustom Hook](/learn/reusing-logic-with-custom-hooks) Anda untuk manampilkan nilai debug yang dapat dibaca:
add `*` for `*debug*`

2023-04-26 17:51 UTC, arganaphang commented on src/content/reference/react/useDebugValue.md
> +Panggil `useDebugValue` di bagian atas [kustom Hook](/learn/reusing-logic-with-custom-hooks) Anda untuk manampilkan nilai debug yang dapat dibaca:
updated 👍

2023-04-26 23:04 UTC, mazipan commented on src/content/reference/react/useDebugValue.md
> +Ini membiarkan komponen memanggil `useOnlineStatus` sebuah label seperti `OnlineStatus: "Online"` ketika Anda memeriksa mereka:
Paragraf ini masih susah ta tangkap maksudnya.

2023-04-26 23:04 UTC, mazipan commented on src/content/reference/react/useDebugValue.md
> +Jangan menambahkan nilai *debug* untuk setiap kustom Hook. Itu paling berharga untuk kustom Hooks yang merupakan bagian dari pustaka bersama dan memiliki struktur data internal kompleks yang sulit un
```suggestion
Jangan menambahkan nilai *debug* untuk setiap kustom Hook. Itu paling berharga untuk kustom Hooks yang merupakan bagian dari pustaka bersama dan memiliki struktur data internal yang kompleks sehingga sulit untuk diperiksa.
```

2023-04-26 23:04 UTC, mazipan commented on src/content/reference/react/useDebugValue.md
> +Fungsi pemformatan Anda akan menerima <CodeStep step={1}>nilai debug</CodeStep> sebagai sebuah parameter dan akan kembali sebuah <CodeStep step={2}>nilai tampilan yang diformat</CodeStep>. Ketika kom
```suggestion
Fungsi pemformatan Anda akan menerima <CodeStep step={1}>nilai debug</CodeStep> sebagai sebuah parameter dan akan mengembalikan sebuah <CodeStep step={2}>nilai tampilan yang telah diformat</CodeStep>. Ketika komponen Anda diperiksa, React DevTools akan memanggil fungsi ini dan menampilkan hasilnya.
```

2023-04-26 23:04 UTC, mazipan commented on src/content/reference/react/useDebugValue.md
> +Ini memungkinkan Anda menghindari menjalankan logika pemformatan yang berpotensi mahal kecuali komponen benar-benar diperiksa. Sebagai contoh, jika `date` merupakan sebuah nilai Tanggal, ini menghind
Expensive di sini kayanya lebih relevan dengan arti "berat"

2023-04-27 03:33 UTC, arganaphang commented on src/content/reference/react/useDebugValue.md
> +Ini membiarkan komponen memanggil `useOnlineStatus` sebuah label seperti `OnlineStatus: "Online"` ketika Anda memeriksa mereka:
updated ya mas, boleh diperiksa lagi apakah sudah cocok, terutama bagian ini.
btw terima kasih feedback nya 👍

2023-04-27 16:48 UTC, arganaphang commented on src/content/reference/react/useDebugValue.md
> +Ini memungkinkan Anda menghindari menjalankan logika pemformatan yang berpotensi berat kecuali komponen benar-benar diperiksa. Sebagai contoh, jika `date` merupakan sebuah nilai Tanggal, ini menghind
i think `mahal` is better than `berat` in this case. How about you sir @mazipan ?

2023-04-27 16:57 UTC, mhaidarhanif commented on src/content/reference/react/useDebugValue.md
> +Ini memungkinkan Anda menghindari menjalankan logika pemformatan yang berpotensi berat kecuali komponen benar-benar diperiksa. Sebagai contoh, jika `date` merupakan sebuah nilai Tanggal, ini menghind
@resir014 can also suggest, we need to clarify this later too in the glossary.

2023-04-28 22:16 UTC, r17x approved these changes

2023-04-28 22:19 UTC, r17x commented
I think it can be merged but need confirm @mhaidarhanif

2023-04-29 05:55 UTC, mazipan approved these changes

2023-04-30 13:23 UTC, arganaphang commented
can we merge this PR sir @resir014?

2023-04-30 21:16 UTC, mhaidarhanif commented on src/content/reference/react/useDebugValue.md
> +Ini memungkinkan Anda menghindari menjalankan logika pemformatan yang berpotensi berat kecuali komponen benar-benar diperiksa. Sebagai contoh, jika `date` merupakan sebuah nilai Tanggal, ini menghind
@mazipan @arganaphang Oke bisa juga seperti itu, `operasi yang mahal/berat (*expensive operation*)`

cc @resir014 @r17x @zainfathoni

2023-04-30 21:18 UTC, mhaidarhanif requested changes
A small improvement.

2023-04-30 21:18 UTC, mhaidarhanif commented on src/content/reference/react/useDebugValue.md
> +Ini memungkinkan Anda menghindari menjalankan logika pemformatan yang berpotensi mahal kecuali komponen benar-benar diperiksa. Sebagai contoh, jika `date` merupakan sebuah nilai *Date*, ini menghinda
To make it a bit easier to understand where it's coming from.

```suggestion
Ini memungkinkan Anda menghindari menjalankan logika pemformatan yang berpotensi mahal/berat (*expensive formatting logic*) kecuali komponen benar-benar diperiksa. Sebagai contoh, jika `date` merupakan sebuah nilai *Date*, ini menghindari pemanggilan `toDateString()` pada setiap render.
```

2023-05-01 15:54 UTC, mhaidarhanif approved these changes

2023-05-01 15:58 UTC, merged