Translate Thinking in React
reactjs/id.react.dev pull request #358
Opened 2023-04-27 17:37 UTC by resir014

Translated the "Thinking in React" page to Indonesian

2023-04-29 03:58 UTC, resir014 commented
@mhaidarhanif @r17x @zainfathoni Ready to review.

2023-04-29 10:24 UTC, mhaidarhanif requested changes
Some early suggestions and feedback to discuss.

2023-04-29 10:24 UTC, mhaidarhanif commented on src/content/learn/thinking-in-react.md
> +React dapat mengubah cara berpikir Anda tentang desain yang Anda lihat dan aplikasi yang Anda buat. Ketika Anda membuat antarmuka pengguna dengan React, pertama-tama Anda akan memecahnya menjadi bebe
`state` need to be italic? Also some people said was confused when being introduced with the name `antarmuka pengguna`.

```suggestion
React dapat mengubah cara berpikir Anda tentang desain yang Anda lihat dan aplikasi yang Anda buat. Ketika Anda membuat antarmuka pengguna (*user interface*) dengan React, pertama-tama Anda akan memecahnya menjadi beberapa bagian yang disebut dengan *komponen*. Kemudian, Anda akan mendeskripsikan *state* visual yang berbeda untuk setiap komponen Anda. Terakhir, Anda akan menghubungkan komponen-komponen Anda bersama-sama sehingga data mengalir melaluinya. Dalam tutorial ini, kami akan memandu Anda melalui proses berpikir untuk membangun tabel data produk yang dapat dicari dengan React.
```

2023-04-29 10:24 UTC, mhaidarhanif commented on src/content/learn/thinking-in-react.md
> +Bayangkan Anda sudah memiliki API JSON dan rancang bangun dari desainer.
To comply with the source, `from a designer` with `a`.

```suggestion
Bayangkan Anda sudah memiliki API JSON dan rancang bangun dari seorang desainer.
```

2023-04-29 10:24 UTC, mhaidarhanif commented on src/content/learn/thinking-in-react.md
> +API JSON mengembalikan beberapa data yang terlihat seperti ini:
Do we need to add this? To make the reading flow better:

```suggestion
API JSON tersebut mengembalikan beberapa data yang terlihat seperti ini:
```

2023-04-29 10:24 UTC, mhaidarhanif commented on src/content/learn/thinking-in-react.md
> +Rancang bangun kita terlihat seperti ini:
Similar to the previous sentence. Also, the source is not `Our mockup`, but `The mockup`.

```suggestion
Rancang bangun tersebut terlihat seperti ini:
```

2023-04-29 10:30 UTC, mhaidarhanif requested changes
Another suggestion is to make the reading flow better.

2023-04-29 10:30 UTC, mhaidarhanif commented on src/content/learn/thinking-in-react.md
> +Mulailah dengan menggambar kotak-kotak di sekitar setiap komponen dan subkomponen dalam rancang bangun dan beri nama. Jika Anda bekerja dengan seorang desainer, mereka mungkin telah menamai komponen-
To make the reading flow better.

```suggestion
Mulailah dengan menggambar kotak-kotak di sekitar setiap komponen dan subkomponen dalam rancang bangun dan berikan nama. Jika Anda bekerja dengan seorang desainer, mereka mungkin telah menamai komponen-komponen ini di alat bantu desain mereka. Tanyakanlah kepada mereka!
```

or

```suggestion
Mulailah dengan menggambar kotak-kotak di sekitar setiap komponen dan subkomponen dalam rancang bangun dan beri mereka nama. Jika Anda bekerja dengan seorang desainer, mereka mungkin telah menamai komponen-komponen ini di alat bantu desain mereka. Tanyakanlah kepada mereka!
```

or

```suggestion
Mulailah dengan menggambar kotak-kotak di sekitar setiap komponen dan subkomponen dalam rancang bangun dan berikan mereka nama. Jika Anda bekerja dengan seorang desainer, mereka mungkin telah menamai komponen-komponen ini di alat bantu desain mereka. Tanyakanlah kepada mereka!
```

2023-04-29 17:12 UTC, r17x requested changes

2023-04-29 17:12 UTC, r17x commented on src/content/learn/thinking-in-react.md
> +1. Identifikasi *setiap* komponen yang merender sesuatu berdasarkan state tersebut.
`merender` -> `me-render`

2023-04-29 19:00 UTC, mhaidarhanif approved these changes
Looks ready, but maybe there are some things to check again. Wait for the others.

2023-04-29 19:50 UTC, r17x requested changes
* word for "state" -> `*state*`
* word for "merender" -> `me-*render*`

2023-04-29 19:50 UTC, r17x commented on src/content/learn/thinking-in-react.md
> +Untuk membuat versi statis dari aplikasi Anda yang merender model data Anda, Anda perlu membuat [komponen](/learn/your-first-component) yang menggunakan kembali komponen lain dan mengirimkan data men
```suggestion
Untuk membuat versi statis dari aplikasi Anda yang me-*render* model data Anda, Anda perlu membuat [komponen](/learn/your-first-component) yang menggunakan kembali komponen lain dan mengirimkan data menggunakan [props.](/learn/passing-props-to-a-component) Props adalah cara untuk mengoper data dari induk ke anak. (Jika Anda sudah terbiasa dengan konsep [state](/learn/state-a-components-memory), jangan gunakan state sama sekali untuk membangun versi statis ini. State hanya diperuntukkan bagi interaktivitas, yaitu data yang berubah seiring waktu. Karena ini adalah versi statis dari aplikasi, Anda tidak memerlukannya).
```

2023-04-29 19:50 UTC, r17x commented on src/content/learn/thinking-in-react.md
> +Setelah membuat komponen, Anda akan memiliki pustaka komponen yang dapat digunakan kembali untuk merender model data Anda. Karena ini adalah aplikasi statis, komponen-komponennya hanya akan mengembal
```suggestion
Setelah membuat komponen, Anda akan memiliki pustaka komponen yang dapat digunakan kembali untuk me-*render* model data Anda. Karena ini adalah aplikasi statis, komponen-komponennya hanya akan mengembalikan JSX. Komponen di bagian atas hirarki (`FilterableProductTable`) akan mengambil model data Anda sebagai *props*. Ini disebut *aliran data satu arah (one-way data flow)* karena data mengalir turun dari komponen tingkat atas ke komponen di bagian bawah pohon.
```

2023-04-29 19:50 UTC, r17x commented on src/content/learn/thinking-in-react.md
> +Setelah Anda memiliki hierarki komponen, sekarang saatnya mengimplementasikan aplikasi Anda. Pendekatan yang paling mudah adalah membuat versi yang merender UI dari model data Anda tanpa menambahkan
```suggestion
Setelah Anda memiliki hierarki komponen, sekarang saatnya mengimplementasikan aplikasi Anda. Pendekatan yang paling mudah adalah membuat versi yang me-*render* UI dari model data Anda tanpa menambahkan interaktivitas apa pun... untuk sementara! Sering kali lebih mudah untuk membuat versi statis terlebih dahulu dan menambahkan interaktivitas kemudian. Membangun versi statis membutuhkan banyak pengetikan dan tidak perlu berpikir, tetapi menambahkan interaktivitas membutuhkan banyak pemikiran dan tidak perlu banyak pengetikan.
```

2023-04-29 19:50 UTC, r17x commented on src/content/learn/thinking-in-react.md
> +1. Identifikasi *setiap* komponen yang merender sesuatu berdasarkan state tersebut.
```suggestion
1. Identifikasi *setiap* komponen yang me-*render* sesuatu berdasarkan *state* tersebut.
```

2023-04-29 19:50 UTC, r17x commented on src/content/learn/thinking-in-react.md
> +3. Tentukan di mana state tersebut harus berada:
```suggestion
3. Tentukan di mana *state* tersebut harus berada:
```

2023-04-29 19:50 UTC, r17x commented on src/content/learn/thinking-in-react.md
> +    1. Sering kali, Anda dapat meletakkan state secara langsung ke dalam induknya.
```suggestion
    1. Sering kali, Anda dapat meletakkan *state* secara langsung ke dalam induknya.
```

2023-04-29 19:50 UTC, r17x commented on src/content/learn/thinking-in-react.md
> +    2. Anda juga dapat menempatkan state ke dalam beberapa komponen di atas induknya.
```suggestion
    2. Anda juga dapat menempatkan *state* ke dalam beberapa komponen di atas induknya.
```

2023-04-29 19:50 UTC, r17x commented on src/content/learn/thinking-in-react.md
> +    3. Jika Anda tidak dapat menemukan komponen yang masuk akal untuk memiliki state, buatlah komponen baru hanya untuk menyimpan state dan tambahkan di suatu tempat di dalam hirarki di atas komponen
```suggestion
    3. Jika Anda tidak dapat menemukan komponen yang masuk akal untuk memiliki *state*, buatlah komponen baru hanya untuk menyimpan *state* dan tambahkan di suatu tempat di dalam hirarki di atas komponen induk umum.
```

2023-04-29 19:50 UTC, r17x commented on src/content/learn/thinking-in-react.md
> +Pada *sandbox* di atas, `ProductTable` dan `SearchBar` membaca props `filterText` dan `inStockOnly` untuk merender tabel, input, dan kotak centang. Sebagai contoh, berikut ini cara `SearchBar` mengis
```suggestion
Pada *sandbox* di atas, `ProductTable` dan `SearchBar` membaca props `filterText` dan `inStockOnly` untuk me-*render* tabel, input, dan kotak centang. Sebagai contoh, berikut ini cara `SearchBar` mengisi nilai input:
```

2023-04-30 12:09 UTC, r17x approved these changes

2023-04-30 12:11 UTC, merged