refactor: translation for reusing logic with custom hooks
reactjs/id.react.dev pull request #363
Opened 2023-04-28 01:30 UTC by rvndaputra

Translation to Bahasa for Reusing Logic with Custom Hooks.

Issue: #330

2023-05-04 05:41 UTC, r17x commented
Any updates @rvndaputra ?

2023-05-09 02:40 UTC, rvndaputra commented
hi @r17x sorry for the delay. i had to go on a business trip. however, i've already worked on it and it's now ready for review. thank you

2023-05-15 17:41 UTC, r17x requested changes

2023-05-15 17:41 UTC, r17x commented on src/content/learn/reusing-logic-with-custom-hooks.md
> +- Semua Hook dijalankan ulang setiap kali komponen Anda dirender ulang.
```suggestion
- Semua Hook dijalankan ulang setiap kali komponen Anda di-render ulang.
```

2023-05-15 17:41 UTC, r17x commented on src/content/learn/reusing-logic-with-custom-hooks.md
> +Ini akan memungkinkan Anda menghilangkan `onTick` dari dependensi Effect Anda. Effect tidak akan disinkronkan setiap kali komponen dirender ulang, sehingga interval perubahan warna latar belakang hal
```suggestion
Ini akan memungkinkan Anda menghilangkan `onTick` dari *dependensi* Effect Anda. Effect tidak akan disinkronkan setiap kali komponen di-*render* ulang, sehingga interval perubahan warna latar belakang halaman tidak akan diatur ulang setiap detik sebelum sempat aktif.
```

2023-05-15 17:41 UTC, r17x commented on src/content/learn/reusing-logic-with-custom-hooks.md
> +Faktanya, ada lima (!) titik merah yang berbeda yang dirender. Anda tidak melihat semuanya karena saat ini mereka semua muncul di posisi yang sama. Inilah yang perlu Anda perbaiki. Yang ingin Anda im
```suggestion
Faktanya, ada lima (!) titik merah yang berbeda yang di-*render*. Anda tidak melihat semuanya karena saat ini mereka semua muncul di posisi yang sama. Inilah yang perlu Anda perbaiki. Yang ingin Anda implementasikan adalah gerakan "bergiliran": setiap titik harus "mengikuti" jalur titik sebelumnya. Misalnya, jika Anda memindahkan kursor dengan cepat, titik pertama harus segera mengikuti dengan segera, titik kedua harus mengikuti titik pertama dengan penundaan kecil, titik ketiga harus mengikuti titik kedua, dan seterusnya.
```

2023-05-15 17:41 UTC, r17x commented on src/content/learn/reusing-logic-with-custom-hooks.md
> +Kode di dalam Custom Hooks akan dijalankan kembali setiap kali komponen Anda dirender ulang. Oleh karena itu, seperti halnya komponen, Custom Hooks [harus bersifat murni.](/learn/keeping-components-p
```suggestion
Kode di dalam kustom Hooks akan dijalankan kembali setiap kali komponen Anda di-*render* ulang. Oleh karena itu, seperti halnya komponen, Custom Hooks [harus bersifat murni.](/learn/keeping-components-pure) Bayangkan kode kustom Hooks sebagai bagian dari badan komponen Anda!
```

2023-05-15 17:41 UTC, r17x commented on src/content/learn/reusing-logic-with-custom-hooks.md
> +Sekarang obrolan tidak akan terhubung kembali setiap kali komponen `ChatRoom` di-render ulang. Berikut adalah demo yang berfungsi penuh untuk meneruskan event handler ke custom Hook yang dapat Anda m
di-render should be italic di-*render*

2023-05-17 18:22 UTC, r17x approved these changes

2023-05-17 18:22 UTC, merged