wip translate Manipulating the DOM with Refs
reactjs/id.react.dev pull request #366
Opened 2023-04-28 01:50 UTC by andriawan

solve issue #330

2023-05-04 05:40 UTC, r17x commented
Any updates @andriawan

2023-05-04 06:00 UTC, andriawan commented
> Any updates @andriawan

Sorry for slow progress...kind of busy at main work... 😅  
promise i will finish the translation this week @r17x

2023-05-05 14:45 UTC, andriawan commented
this PR is ready for review. cc @r17x @zainfathoni @mhaidarhanif @resir014 @mazipan

2023-05-06 07:04 UTC, r17x requested changes

2023-05-06 07:04 UTC, r17x commented on src/content/learn/manipulating-the-dom-with-refs.md
> +React secara otomatis memperbarui [DOM (*Document Object Model*)](https://developer.mozilla.org/docs/Web/API/Document_Object_Model/Introduction) agar sesuai dengan keluaran *render*, sehingga kompone
```suggestion
React secara otomatis memperbarui [DOM (*Document Object Model*)](https://developer.mozilla.org/docs/Web/API/Document_Object_Model/Introduction) agar sesuai dengan keluaran *render*, sehingga komponen Anda tidak perlu sering memanipulasinya. Namun, terkadang Anda mungkin perlu mengakses elemen DOM yang dikelola oleh React--misalnya, untuk memberikan fokus pada sebuah *node*, menggulir ke sana, atau mengukur ukuran dan posisinya. Tidak ada cara bawaan untuk melakukan hal-hal tersebut di React, sehingga Anda memerlukan *ref* ke simpul DOM.
```

2023-05-06 07:04 UTC, r17x commented on src/content/learn/manipulating-the-dom-with-refs.md
> +- Bagaimana cara mengakses sebuah *node* DOM yang diatur React dengan atribut `ref`
```suggestion
- Bagaimana cara mengakses sebuah simpul DOM yang diatur React dengan atribut `ref`
```

bisa juga menggunakan `simpul (*node*)`

2023-05-06 07:04 UTC, r17x commented on src/content/learn/manipulating-the-dom-with-refs.md
> +- Bagaimana cara mengakses *node* DOM dari komponen lain
Idem

2023-05-06 07:04 UTC, r17x commented on src/content/learn/manipulating-the-dom-with-refs.md
> +Untuk mengakses sebuah *node* DOM yang diatur React, pertama, impor Hook `useRef`:
idem

2023-05-06 07:04 UTC, r17x commented on src/content/learn/manipulating-the-dom-with-refs.md
> +Terakhir, oper ke DOM node sebagai atribut `ref`:
idem dan beberapa line kebawah

2023-05-06 07:25 UTC, andriawan commented
been already improved translation `node` in the latest commit. cc @r17x

2023-05-07 20:25 UTC, r17x approved these changes
Thanks for your contribution @andriawan 🚀

2023-05-07 20:27 UTC, merged