Translation for `Hooks` : `useTransition`
reactjs/id.react.dev pull request #371
Opened 2023-04-28 03:15 UTC by dickygiancini

Apologies for any mistranslation or misspelling terms. It's my first time doing Open Source project so any criticues and suggestions are very welcome

2023-04-28 07:38 UTC, r17x commented on src/content/reference/react/useTransition.md
> +`useTransition` adalah sebuah React Hook yang memungkinkan Anda merubah suatu state tanpa memblokir UI.
```suggestion
`useTransition` adalah sebuah React Hook yang memungkinkan Anda merubah suatu *state* tanpa memblokir *UI*.
```

2023-04-28 07:39 UTC, r17x commented on src/content/reference/react/useTransition.md
> +Panggil `useTransition` pada level teratas komponen Anda untuk menandai beberapa perubahan state sebagai transisi.
Same with this suggestion https://github.com/reactjs/id.react.dev/pull/371/files#r1180040206

2023-04-28 07:41 UTC, r17x commented on src/content/reference/react/useTransition.md
> +`useTransition` mengembalikan array dengan tepat dua item:
When we referenced by glossary. Array is `Senarai`. 

CMIIW @mhaidarhanif @resir014

2023-04-28 07:41 UTC, r17x commented on src/content/reference/react/useTransition.md
> +1. Flag `isPending` yang memberitahukan Anda bahwa terdapat transisi yang tertunda.
Flag bisa diubah menjadi `Penanda`

2023-04-28 07:44 UTC, r17x requested changes
Beberapa kata yang perlu dibuat menjadi italic dan sugesti kata yang dijadikan kata pengganti.

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Panggil `useTransition` pada level teratas komponen Anda untuk menandai beberapa perubahan state sebagai transisi.
```suggestion
Panggil `useTransition` pada level teratas komponen Anda untuk menandai beberapa perubahan *state* sebagai transisi.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +`useTransition` mengembalikan array dengan tepat dua item:
```suggestion
`useTransition` mengembalikan senarai dengan tepat dua item:
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Fungsi `startTransition` yang dikembalikan oleh `useTransition` memungkinkan Anda menandai perubahan state sebagai transisi.
```suggestion
Fungsi `startTransition` yang dikembalikan oleh `useTransition` memungkinkan Anda menandai perubahan *state* sebagai transisi.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +* `scope`: Fungsi yang merubah beberapa state dengan memanggil satu atau lebih [fungsi `set`.](/reference/react/useState#setstate) React segera memanggil `scope` dengan tanpa parameter dan menandai s
```suggestion
* `scope`: Fungsi yang mengubah beberapa *state* dengan memanggil satu atau lebih [fungsi `set`.](/reference/react/useState#setstate) React segera memanggil `scope` dengan tanpa parameter dan menandai semua perubahan *state* yang dijadwalkan secara sinkron saat fungsi `scope` dipanggil sebagai transisi. Mereka akan menjadi [non-blocking](#marking-a-state-update-as-a-non-blocking-transition) dan [tidak akan menampilkan indikator *render* yang tidak perlu.](#preventing-unwanted-loading-indicators)
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +* `useTransition` adalah sebuah Hook, sehingga hanya bisa dipanggil di dalam komponen atau Hook khusus. Jika Anda ingin memulai sebuah transisi di tempat lain (contoh, dari data library), sebaiknya p
```suggestion
* `useTransition` adalah sebuah Hook, sehingga hanya bisa dipanggil di dalam komponen atau Hook *custom*. Jika Anda ingin memulai sebuah transisi di tempat lain (contoh, dari data *library*), sebaiknya panggil [`startTransition`](/reference/react/startTransition) sebagai gantinya.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +* Anda dapat membungkus perubahan menjadi transisi hanya jika Anda memiliki akses pada fungsi `set` pada state tersebut. Jika Anda ingin memulai sebuah transisi sebagai balasan dari beberapa prop ata
```suggestion
* Anda dapat membungkus perubahan menjadi transisi hanya jika Anda memiliki akses pada fungsi `set` pada *state* tersebut. Jika Anda ingin memulai sebuah transisi sebagai balasan dari beberapa *prop* atau nilai Hook *custom*, coba gunakan [`useDeferredValue`](/reference/react/useDeferredValue) sebagai gantinya.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +* Perubahan state yang ditandai sebagai transisi akan terganggu oleh perubahan state lainnya. Contohnya, jika anda merubah komponen chart di dalam transisi, namun kemudian memulai mengetik dalam inpu
```suggestion
* Perubahan *state* yang ditandai sebagai transisi akan terganggu oleh perubahan *state* lainnya. Contohnya, jika anda mengubah komponen chart di dalam transisi, namun kemudian memulai mengetik dalam input ketika chart sedang di tengah me*render* ulang, React akan me*render* ulang pekerjaan pada komponen chart setelah mengerjakan perubahan pada input.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +* Perubahan transisi tidak dapat digunakan untuk mengontrol input text.
```suggestion
* Perubahan transisi tidak dapat digunakan untuk mengontrol input teks.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Panggil `useTransition` pada level teratas komponen Anda untuk menandai perubahan state sebagai *transisi* non-blocking.
```suggestion
Panggil `useTransition` pada level teratas komponen Anda untuk menandai perubahan *state* sebagai *transisi* non-blocking.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +`useTransition` mengembalikan sebuah array dengan tepat dua item:
```suggestion
`useTransition` mengembalikan sebuah senarai dengan tepat dua item:
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +2. Fungsi <CodeStep step={2}>`startTransition`</CodeStep> yang memungkinkan Anda menandai perubahan state sebagai transisi.
```suggestion
2. Fungsi <CodeStep step={2}>`startTransition`</CodeStep> yang memungkinkan Anda menandai perubahan *state* sebagai transisi.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Kemudian Anda dapat menandai perubahan state sebagai transisi seperti berikut:
```suggestion
Kemudian Anda dapat menandai perubahan *state* sebagai transisi seperti berikut:
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Pada contoh berikut ini, tab "Posts" ini **Dipelankan secara artifisial** sehingga akan memakan waktu setidaknya satu detik untuk render.
```suggestion
Pada contoh berikut ini, tab "Posts" ini **Dipelankan secara artifisial** sehingga akan memakan waktu setidaknya satu detik untuk *render*.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Tekan "Posts" kemudian segera tekan "Contact". Perhatikan bahwa ini akan mengganggu muatan "Posts" yang lambat. Tab "Contact" akan tampil segera. Karena perubahan state ini ditandai sebagai transisi,
```suggestion
Tekan "Posts" kemudian segera tekan "Contact". Perhatikan bahwa ini akan mengganggu muatan "Posts" yang lambat. Tab "Contact" akan tampil segera. Karena perubahan *state* ini ditandai sebagai transisi, me*render* ulang yang lambat tidak akan membekukan tampilan pengguna.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Pada contoh berikut, tab "Posts" juga **Dipelankan secara artifisial** sehingga akan memakan waktu setidaknya satu detik untuk render. Berbeda dengan contoh sebelumnya, perubahan state ini **bukanlah
```suggestion
Pada contoh berikut, tab "Posts" juga **Dipelankan secara artifisial** sehingga akan memakan waktu setidaknya satu detik untuk *render*. Berbeda dengan contoh sebelumnya, perubahan *state* ini **bukanlah sebuah transisi.**
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Tekan "Posts" kemudian segera tekan "Contact". Perhatikan bahwa aplikasi membeku ketika render tab yang lambat, dan UI menjadi tidak responsive. Perubahan state ini bukanlah sebuah transisi, sehingga
```suggestion
Tekan "Posts" kemudian segera tekan "Contact". Perhatikan bahwa aplikasi membeku ketika render tab yang lambat, dan UI menjadi tidak responsive. Perubahan *state* ini bukanlah sebuah transisi, sehingga merender ulang yang lambat membekukan tampilan pengguna.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Anda dapat merubah state komponen induk dari panggilan `useTransition` juga. Contohnya, komponen `TabButton` ini membungkus logika komponen `onClick` dalam sebuah transisi:
```suggestion
Anda dapat mengubah *state* komponen induk dari panggilan `useTransition` juga. Contohnya, komponen `TabButton` ini membungkus logika komponen `onClick` dalam sebuah transisi:
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Karena komponen induk merubah statenya di dalam event handler `onClick`, perubahan state tersebut akan ditandai sebagai transisi. Inilah mengapa, seperti pada contoh diawal, Anda dapat menekan pada "
```suggestion
Karena komponen induk merubah *state*nya di dalam event handler `onClick`, perubahan *state* tersebut akan ditandai sebagai transisi. Inilah mengapa, seperti pada contoh di awal, Anda dapat menekan pada "Posts" dan kemudian segera menekan "Contact". Mengubah tab yang dipilih akan ditandai sebagai transisi, sehingga itu tidak memblokir tampilan pengguna.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Anda dapat menggunakan nilai boolean `isPending` yang dikembalikan oleh `useTransition` untuk menandai ke pengguna bahwa transisi sedang berjalan. Contohnya, tombol tab dapat memiliki state visual sp
```suggestion
Anda dapat menggunakan nilai boolean `isPending` yang dikembalikan oleh `useTransition` untuk menandai ke pengguna bahwa transisi sedang berjalan. Contohnya, tombol tab dapat memiliki *state* visual special "pending":
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Menyembunyikan seluruh tab container untuk menampilkan indikator loading akan mengarahkan ke pengalaman pengguna yang gemuruh. Jika Anda menambahkan `useTransition` ke `TabButton`, Anda bisa sebagai
```suggestion
Menyembunyikan seluruh tab container untuk menampilkan indikator loading akan mengarahkan ke pengalaman pengguna yang gemuruh. Jika Anda menambahkan `useTransition` ke `TabButton`, Anda bisa sebagai gantinya mengindikasi tampilan *state* pending di tombol tab sebagai gantinya.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Ini dikarenakan transisi adalah non-blocking, namun merubah input dalam respon untuk merubah *event* seharusnya bekerja secara sinkronus. Jika Anda ingin menjalankan transisi sebagai respon untuk men
```suggestion
Ini dikarenakan transisi adalah non-blocking, namun mengubah input dalam respon untuk mengubah *event* seharusnya bekerja secara sinkron. Jika Anda ingin menjalankan transisi sebagai respon untuk menulis, Anda memiliki dua opsi:
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +2. Kalau tidak, Anda dapat memiliki satu variabel state, dan tambahkan [`useDeferredValue`](/reference/react/useDeferredValue) yang akan "lag" dibelakang nilai asli. Ini akan men*trigger* merender ul
```suggestion
1. Anda dapat mendeklarasikan dua variabel *state* berbeda: satu untuk *state* masukan ( yang selalu berubah secara sinkron), dan satu yang akan Anda ubah dalam transisi. Ini memungkinkan Anda mengendalikan masukan menggunakan *state* sinkron, dan mengirim variabel *state* transisi (yang akan "lag" dibelakang masukan) ke sisa logika *rendering* Anda.
2. Kalau tidak, Anda dapat memiliki satu variabel *state*, dan tambahkan [`useDeferredValue`](/reference/react/useDeferredValue) yang akan "lag" dibelakang nilai asli. Ini akan men*trigger* me*render* ulang non-blocking untuk "mengejar" dengan nilai baru secara otomatis.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Ketika Anda membungkus perubahan state di dalam transisi, pastikan bahwa itu terjadi *saat* memanggil `startTransition`:
```suggestion
Ketika Anda membungkus perubahan *state* di dalam transisi, pastikan bahwa itu terjadi *saat* memanggil `startTransition`:
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Fungsi yang Anda kirimkan ke `startTransition` harus sinkronus.
```suggestion
Fungsi yang Anda kirimkan ke `startTransition` harus sinkron.
```

2023-04-28 07:50 UTC, itsfaqih commented on src/content/reference/react/useTransition.md
> +Anda tidak dapat memanggil `useTransition` diluar sebuah komponen karena ini adalah sebuah Hook. Dalam kasus ini, sebaiknya gunakanlah metode [`startTransition`](/reference/react/startTransition). It
```suggestion
Anda tidak dapat memanggil `useTransition` di luar sebuah komponen karena ini adalah sebuah Hook. Dalam kasus ini, sebaiknya gunakanlah *method* [`startTransition`](/reference/react/startTransition). Itu bekerja dengan cara yang sama, namun itu tidak dapat memberikan indikator `isPending`.
```

2023-04-28 10:25 UTC, dickygiancini commented
> Beberapa kata yang perlu dibuat menjadi italic dan sugesti kata yang dijadikan kata pengganti.

I will change them as soon as possible, thank you!

2023-04-28 10:47 UTC, dickygiancini commented on src/content/reference/react/useTransition.md
> +**Ini diharapkan untuk mencetak 1, 2, 3.** Fungsi yang Anda berikan ke `startTransition` tidak tertunda. Tidak seperti milik browser `setTimeout`, hal tersebut nantinya tidak menjalankan *callback*.
Thank you for all the translation suggestions!

2023-04-28 14:42 UTC, dickygiancini reviewed
Resolve original terms from regular text to italic

2023-04-28 14:57 UTC, mhaidarhanif approved these changes
@r17x can check again, most requests have been resolved.

2023-04-29 17:06 UTC, r17x approved these changes

2023-04-29 17:08 UTC, merged