docs: translating renderToStaticNodeStream
reactjs/id.react.dev pull request #476
Opened 2023-04-28 07:02 UTC by rimamei

Closes https://github.com/reactjs/id.react.dev/issues/461

WIP translation to Bahasa for renderToStaticNodeStream.

Reference: https://github.com/reactjs/id.react.dev/issues/330

2023-04-29 20:57 UTC, r17x requested changes

2023-04-29 20:57 UTC, r17x commented on src/content/reference/react-dom/server/renderToStaticNodeStream.md
> +`renderToStaticNodeStream` merender sebuah pohon React yang tidak interaktif ke dalam sebuah [*Node.js Readable Stream*.](https://nodejs.org/api/stream.html#readable-streams)
```suggestion
`renderToStaticNodeStream` me-*render* sebuah pohon (*tree*) React yang tidak interaktif ke dalam sebuah [*Node.js Readable Stream*.](https://nodejs.org/api/stream.html#readable-streams)
```

2023-04-29 20:57 UTC, r17x commented on src/content/reference/react-dom/server/renderToStaticNodeStream.md
> +* `reactNode`: Sebuah *node* React yang ingin kalian render ke dalam HTML. Misalnya, sebuah elemen JSX seperti `<Page />`.
```suggestion
* `reactNode`: Sebuah *node* React yang ingin kalian *render* ke dalam HTML. Misalnya, sebuah elemen JSX seperti `<Page />`.
```

2023-04-29 20:57 UTC, r17x commented on src/content/reference/react-dom/server/renderToStaticNodeStream.md
> +Sebuah [*Node.js Readable Stream*](https://nodejs.org/api/stream.html#readable-streams) yang menghasilkan sebuah *string* HTML. HTML yang dihasilkan tidak bisa dihidrasi di sisi klien.
```suggestion
Sebuah [*Node.js Readable Stream*](https://nodejs.org/api/stream.html#readable-streams) yang menghasilkan sebuah *string* HTML. HTML yang dihasilkan tidak bisa dihidrasi (*hydrated*) di sisi klien.
```

2023-04-29 20:57 UTC, r17x commented on src/content/reference/react-dom/server/renderToStaticNodeStream.md
> +* Keluaran `renderToStaticNodeStream` tidak dapat dihidrasi.
```suggestion
* Keluaran `renderToStaticNodeStream` tidak dapat dihidrasi (*hydrated*).
```

2023-04-29 20:57 UTC, r17x commented on src/content/reference/react-dom/server/renderToStaticNodeStream.md
> +* *Stream* yang dikembalikan merupakan sebuah *byte stream* yang dienkode dalam utf-8. Jika kalian membutuhkan sebuah *stream* yang dienkode lainnya, lihatlah ke sebuah proyek seperti [iconv-lite](ht
```suggestion
* *Stream* yang dikembalikan merupakan sebuah *byte stream* yang *encoded* dalam *utf-8*. Jika kalian membutuhkan sebuah *stream* lain yang di-*encode*, lihatlah ke sebuah proyek seperti [iconv-lite](https://www.npmjs.com/package/iconv-lite), yang memberikan transformasi aliran untuk *transcoding* teks.
```

2023-04-29 20:57 UTC, r17x commented on src/content/reference/react-dom/server/renderToStaticNodeStream.md
> +### Merender sebuah pohon React sebagai HTML statis ke dalam sebuah *Node.js Readable Stream* {/*rendering-a-react-tree-as-static-html-to-a-nodejs-readable-stream*/}
```suggestion
### Me-render sebuah pohon React sebagai HTML statis ke dalam sebuah Node.js Readable Stream {/*rendering-a-react-tree-as-static-html-to-a-nodejs-readable-stream*/}
```

2023-04-29 20:57 UTC, r17x commented on src/content/reference/react-dom/server/renderToStaticNodeStream.md
> +Metode ini merender **HTML tidak interaktif yang tidak bisa dihidrasi.** Ini berguna jika kalian ingin menggunakan React sebagai sebuah generator halaman statis sederhana, atau jika kalian merender k
```suggestion
*Method* ini me-*render* **HTML tidak interaktif yang tidak bisa dihidrasi (*hydrated*).** Ini berguna jika kalian ingin menggunakan React sebagai sebuah *generator* halaman statis sederhana, atau jika kalian me-*render* konten statis seperti email.
```

2023-04-30 03:27 UTC, rimamei commented
There's another change that I add. I change `kalian` to `anda` as other PR use anda and use `caveats` as it is based on this PR review https://github.com/reactjs/id.react.dev/pull/364

2023-04-30 05:27 UTC, r17x approved these changes

2023-04-30 05:31 UTC, merged