Translation of `startTransition`
reactjs/id.react.dev pull request #487
Opened 2023-04-28 15:11 UTC by lauslim12

Menambahkan terjemahan Bahasa Indonesia untuk `startTransition`.

2023-04-28 15:16 UTC, lauslim12 commented on src/content/reference/react/startTransition.md
> +* Anda hanya dapat menempatkan pembaruan _state_ ke dalam transisi bila Anda memiliki akses terhadap fungsi `set` dari _state_ tersebut. Jika Anda ingin memulai sebuah transisi sebagai respons terhad
Ketimbang menggunakan `membungkus sebuah pembaruan state di dalam transisi`, pendapat subjektif saya lebih natural apabila kita melakukan parafrase menjadi `menempatkan pembaruan state ke dalam transisi`.

2023-04-28 15:16 UTC, lauslim12 commented on src/content/reference/react/startTransition.md
> +Transisi memungkinkan pembaruan antarmuka pengguna (_user interface_) tetap responsif, bahkan dalam gawai yang relatif lamban.
Subjektif: Menurut saya lebih baik dijelaskan apa arti dari `antarmuka pengguna`, karena terkadang beberapa orang masih agak kaku dan terasa lebih natural apabila menggunakan kata `user interface`.

2023-04-28 18:23 UTC, mhaidarhanif commented on src/content/reference/react/startTransition.md
> +* Anda hanya dapat menempatkan pembaruan _state_ ke dalam transisi bila Anda memiliki akses terhadap fungsi `set` dari _state_ tersebut. Jika Anda ingin memulai sebuah transisi sebagai respons terhad
Yes, `menempatkan pembaruan state ke dalam transisi` seems better.

2023-04-28 18:38 UTC, mhaidarhanif requested changes
Let's first replace all `_` with `*` as with other merged PRs for consistency.

2023-04-28 18:38 UTC, mhaidarhanif commented on src/content/reference/react/startTransition.md
> +`startTransition` memungkinkan Anda memperbarui sebuah _state_ tanpa memblokir proses _rendering_ pada UI.
Let's use `*` as with other merged PRs.

```suggestion
`startTransition` memungkinkan Anda memperbarui sebuah *state* tanpa memblokir proses *render* pada UI.
```

2023-04-28 18:38 UTC, mhaidarhanif commented on src/content/reference/react/startTransition.md
> +Fungsi `startTransition` memungkinkan Anda menandai sebuah pembaruan _state_ sebagai transisi.
Idem

```suggestion
Fungsi `startTransition` memungkinkan Anda menandai sebuah pembaruan *state* sebagai transisi.
```

2023-04-29 20:30 UTC, mhaidarhanif approved these changes
Approved and let's wait for the others

2023-04-29 21:26 UTC, r17x approved these changes

2023-04-29 21:27 UTC, merged