docs: translate `renderToReadableStream` section
reactjs/id.react.dev pull request #497
Opened 2023-04-29 05:45 UTC by hisamafahri

Close #459

2023-05-04 01:43 UTC, mazipan commented
Is this ready to review @hisamafahri?

2023-05-04 01:48 UTC, hisamafahri commented
@mazipan not yet. This section's quite a lot.

2023-05-04 04:18 UTC, hisamafahri commented
@mazipan this is ready for review now 👍

2023-05-24 06:17 UTC, resir014 commented
Hi @hisamafahri, there's a merge conflict. Please resolve it first before proceeding with review.

2023-05-25 03:11 UTC, mazipan commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +* `allReady`: _Promise_ yang diselesaikan saat semua preose _render_ selesai, termasuk [_shell_](#specifying-what-goes-into-the-shell) dan semua [konten](#streaming-more-content-as-it-loads) tambahan
Pake `*` buat bikin italic, biar konsisten dengan halaman lainnya

2023-05-26 14:01 UTC, r17x commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +### Memulihkan dari kesalahan di dalam *shell* {/*recovering-from-errors-inside-the-shell*/}
Italic tak perlu ada di Heading

2023-05-26 14:01 UTC, r17x commented on src/content/reference/react-dom/server/renderToReadableStream.md
> +### Memulihkan dari kesalahan di luar *shell* {/*recovering-from-errors-outside-the-shell*/}
idem

2023-05-26 14:02 UTC, r17x requested changes
Italic tak perlu ada di Heading

2023-05-28 09:47 UTC, r17x approved these changes

2023-05-28 09:53 UTC, merged