docs: translate Choosing State Structure
reactjs/id.react.dev pull request #502
Opened 2023-04-29 12:38 UTC by dzakiafif

Pages: https://react.dev/learn/choosing-the-state-structure
Closes: #380

2023-05-07 10:52 UTC, r17x approved these changes

2023-05-08 04:13 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +Tujuan di balik prinsip-prinsip ini adalah membuat *state* mudah diperbarui tanpa memperkenalkan kesalahan. Menghapus *data* yang redundan dan duplikat dari *state* membantu memastikan bahwa semua ba
mengnormalisasi = menormalisasi

```suggestion
Tujuan di balik prinsip-prinsip ini adalah membuat *state* mudah diperbarui tanpa memperkenalkan kesalahan. Menghapus *data* yang redundan dan duplikat dari *state* membantu memastikan bahwa semua bagian *state* tetap sinkron. Ini mirip dengan bagaimana seorang insinyur *database* mungkin ingin [menormalisasi struktur *database*](https://docs.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description) untuk mengurangi kemungkinan *bug*. Untuk mem-*parafrase* Albert Einstein, **"Jadikan *state* Anda sesederhana mungkin - tetapi tidak lebih sederhana dari itu.."**
```

2023-05-08 04:13 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +Tujuan di balik prinsip-prinsip ini adalah membuat *state* mudah diperbarui tanpa memperkenalkan kesalahan. Menghapus *data* yang redundan dan duplikat dari *state* membantu memastikan bahwa semua ba
"But no simpler" diterjemahkan jadi "tetapi tidak lebih sederhana dari itu.." kok rada gimana ya?

@zainfathoni @mhaidarhanif @resir014 @r17x

2023-05-08 04:13 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +Di sini, sebuah variabel *state* `color` di-inisialisasi dengan *prop* `messageColor`. Masalahnya adalah bahwa **jika komponen induk memberikan nilai `messageColor` berbeda (misalnya, `'red'` daripad
```suggestion
Di sini, sebuah variabel *state* `color` di-inisialisasi dengan *prop* `messageColor`. Masalahnya adalah bahwa **jika komponen induk memberikan nilai `messageColor` berbeda (misalnya, `'red'` daripada `'blue'`), variabel *state* `color` tidak akan diperbarui!**  State hanya diinisialisasi selama *render* pertama.
```

2023-05-08 04:13 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +Sekarang jika Anda mengedit *item* yang *dipilih*, pesan di bawahnya akan segera diperbarui. Ini karena `setItems` memicu *render* ulang, dan `items.find(...)` akan menemukan item dengan judul yang d
```suggestion
Sekarang jika Anda mengubah *item* yang *dipilih*, pesan di bawahnya akan segera diperbarui. Ini karena `setItems` memicu *render* ulang, dan `items.find(...)` akan menemukan item dengan judul yang diperbarui. Anda tidak perlu menyimpan *item* yang dipilih di *state*, karena hanya *ID* yang dipilih yang penting. Yang lain dapat dihitung selama *render*.
```

2023-05-08 04:13 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +*Data restructuring* ini mungkin mengingatkan Anda melihat table *database*:
```suggestion
Penataan data ini mungkin mengingatkan Anda pada tabel di basis data:
```

2023-05-08 04:13 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +**Sekarang karena *state*-nya "datar" (juga dikenal sebagai "dinarmalisasi"), memperbarui *item* yang bersarang menjadi lebih mudah.**
Typo
```suggestion
**Sekarang karena *state*-nya "datar" (juga dikenal sebagai "dinormalisasi"), memperbarui *item* yang bersarang menjadi lebih mudah.**
```

2023-05-08 04:13 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +* Jika memperbarui *state* yang sangat berlapis-lapis menjadi rumit, coba datanya di-flat-kan.
```suggestion
* Jika memperbarui *state* yang sangat berlapis-lapis menjadi rumit, coba didatarkan.
```

2023-05-08 04:13 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +#### Sesuaikan komponen yang tidak terupdate {/*fix-a-component-thats-not-updating*/}
```suggestion
#### Sesuaikan komponen yang tidak terbarui {/*fix-a-component-thats-not-updating*/}
```

2023-05-08 04:13 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +Daftar bawaan ini memiliki *footer* yang menunjukkan berapa *item* yang sudah dikemas, dan berapa total *item* yang ada. Pada awalnya, *footer* ini tampak berfungsi, namun terdapat *bug*. Sebagai con
```suggestion
Daftar bawaan ini memiliki *footer* yang menunjukkan berapa *item* yang sudah dikemas, dan berapa total *item* yang ada. Pada awalnya, *footer* ini tampak berfungsi, namun terdapat *bug*. Sebagai contoh, jika Anda menandai sebuah *item* sebagai sudah dikemas, lalu menghapusnya, hitungan tidak akan diperbarui dengan benar. Perbaiki hitungannya agar selalu benar.
```

2023-05-08 04:13 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +Ada daftar `letters` dalam *state*. Ketika kamu mengarahkan atau fokus pada huruf tertentu, huruf tersebut di-*highlight*. Huruf yang saat ini di-*highlight* disimpan dalam variabel *state* `highligh
highlight = sorot

```suggestion
Ada daftar `letters` dalam *state*. Ketika kamu mengarahkan atau fokus pada huruf tertentu, huruf tersebut disorot. Huruf yang saat ini disorot disimpan dalam variabel *state* `highlightedLetter`. Kamu dapat "menyimpan" dan "menghapus" huruf tertentu, yang memperbarui senarai `letters` dalam *state*.
```

2023-05-08 04:13 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +Kode ini berfungsi, tetapi terdapat sedikit *glitch UI*. Saat kamu menekan "*Star*" atau "*Unstar*", *highlighting*-nya hilang sejenak. Namun, itu muncul kembali begitu kamu memindahkan *pointer* ata
```suggestion
Kode ini berfungsi, tetapi terdapat sedikit *glitch UI*. Saat kamu menekan "*Star*" atau "*Unstar*", sorotannya hilang sejenak. Namun, itu muncul kembali begitu kamu memindahkan *pointer* atau beralih ke huruf lain dengan *keyboard*. Mengapa ini terjadi? Perbaiki agar *highlighting* tidak hilang setelah klik tombol.
```

2023-05-08 07:11 UTC, resir014 commented on src/content/learn/choosing-the-state-structure.md
> +Tujuan di balik prinsip-prinsip ini adalah membuat *state* mudah diperbarui tanpa memperkenalkan kesalahan. Menghapus *data* yang redundan dan duplikat dari *state* membantu memastikan bahwa semua ba
@mazipan "tetapi jangan terlalu sederhana.."

```suggestion
Tujuan di balik prinsip-prinsip ini adalah membuat *state* mudah diperbarui tanpa memperkenalkan kesalahan. Menghapus *data* yang redundan dan duplikat dari *state* membantu memastikan bahwa semua bagian *state* tetap sinkron. Ini mirip dengan bagaimana seorang insinyur *database* mungkin ingin [mengnormalisasi struktur *database*](https://docs.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description) untuk mengurangi kemungkinan *bug*. Untuk mem-*parafrase* Albert Einstein, **"Jadikan *state* Anda se-sederhana mungkin--tetapi jangan terlalu sederhana.."**
```

2023-05-08 07:16 UTC, resir014 requested changes
Some changes requested. Make sure to take a look at @mazipan's review items.

2023-05-08 07:21 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +Tujuan di balik prinsip-prinsip ini adalah membuat *state* mudah diperbarui tanpa memperkenalkan kesalahan. Menghapus *data* yang redundan dan duplikat dari *state* membantu memastikan bahwa semua ba
+1 from me

2023-05-10 23:44 UTC, dzakiafif commented
> Some changes requested. Make sure to take a look at @mazipan's review items.

ok. will update as soon as possible mas. thanks.

2023-05-13 03:51 UTC, dzakiafif commented
sorry my bad. i forget to change github account T.T is it ok?

2023-05-25 03:47 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +Menata struktur *state* dengan baik dapat membuat perbedaan antara komponen yang mudah di-modifikasi dan di-*debug*, dan komponen yang menjadi sumber kesalahan yang konstan. Berikut adalah beberapa t
```suggestion
Menata struktur *state* dengan baik dapat membuat perbedaan antara komponen yang mudah dimodifikasi dan di-*debug*, dan komponen yang menjadi sumber kesalahan yang konstan. Berikut adalah beberapa tips yang harus Anda pertimbangkan saat menata struktur *state*.
```

2023-05-31 01:36 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +Ubah struktur *state* untuk mendukung pemilihan ganda. (Bagaimana Anda akan mengatur struktur tersebut? Pikirkan tentang ini sebelum menulis kode.) Setiap *checkbox* harus menjadi independen dari yan
```suggestion
Ubah struktur *state* untuk mendukung pemilihan ganda. (Bagaimana Anda akan mengatur struktur tersebut? Pikirkan tentang ini sebelum menulis kode.) Setiap *checkbox* harus menjadi independen dari yang lain. Mengeklik huruf yang telah terpilih harus membatal pilihannya. Terakhir, *footer* harus menunjukkan jumlah *item* yang dipilih dengan benar.
```

2023-05-31 01:38 UTC, mazipan commented on src/content/learn/choosing-the-state-structure.md
> +## Prinsip-prinsip untuk menata *state*. {/*principles-for-structuring-state*/}
Kelebihan titik pada heading

2023-05-31 01:38 UTC, mazipan approved these changes

2023-06-03 05:13 UTC, resir014 commented on src/content/learn/choosing-the-state-structure.md
> +## Prinsip-prinsip untuk menata *state*. {/*principles-for-structuring-state*/}
```suggestion
## Prinsip-prinsip untuk menata state {/*principles-for-structuring-state*/}
```

2023-06-03 05:14 UTC, resir014 commented on src/content/learn/choosing-the-state-structure.md
> +      // Lalu hapus ID ini dari senarai tersebut.
```suggestion
      // Jika iya, hapus ID ini dari senarai tersebut.
```

2023-06-03 05:15 UTC, resir014 approved these changes
All good. Thanks!

2023-06-04 15:38 UTC, merged