Translate `rect-dom/client` → `createRoot` to Bahasa Indonesia
reactjs/id.react.dev pull request #514
Opened 2023-04-30 06:18 UTC by chez14

Closes #454 

## Description

Translate the `react-dom/client` → `createRoot` page.
Page URL: https://react.dev/reference/react-dom/client/createRoot

References:
- #330+
- #454+

2023-04-30 06:38 UTC, chez14 commented
Hi @resir014 / @zainfathoni, I've translated the page and this MR is ready for review.

Tough, I still have questions:
- I noticed that some titles such as ["Parameters"][ref-para] and ["Returns"][ref-retr] are not translated in one of the Sepuh's MR, and I honestly feel like this can be translated properly as "Parameter" and "Pengembalian". Should we do that? (In current MR, I left it as is)
- Should I translate following terms?
  - "server-side rendering (SSR)" → "Perenderan pada sisi server (server-side rendering, SSR)"
  - "static site generation (SSG)" → "Pembangunan situs statik (static site generation, SSG)"
  
  Currently I've left it as is and treat it as loan word (term?).

Also note:
- I noticed that loanwords that have been 'glued' with _imbuhan_ such as ["merender"][ref-render] currently don't need to be italicized or separated with `-`, I applied this rule for "render" and "unmount".
- I did not translate the error messages in the Troubleshooting part because I don't think error messages in React is localized too. Please let me know if this should actually be translated too.

Thank you so much!

[ref-para]: https://github.com/reactjs/id.react.dev/pull/351/files#diff-434456b83005426d91d6683a04db292dea22bc6fee2608038715c6b807f28882L35
[ref-retr]: https://github.com/reactjs/id.react.dev/pull/351/files#diff-434456b83005426d91d6683a04db292dea22bc6fee2608038715c6b807f28882L39
[ref-render]: https://github.com/reactjs/id.react.dev/pull/351/files#r1179192132

2023-05-01 15:58 UTC, zainfathoni commented
> Hi @resir014 / @zainfathoni, I've translated the page and this MR is ready for review.
> 
> Tough, I still have questions:
> 
> * I noticed that some titles such as ["Parameters"](https://github.com/reactjs/id.react.dev/pull/351/files#diff-434456b83005426d91d6683a04db292dea22bc6fee2608038715c6b807f28882L35) and ["Returns"](https://github.com/reactjs/id.react.dev/pull/351/files#diff-434456b83005426d91d6683a04db292dea22bc6fee2608038715c6b807f28882L39) are not translated in one of the Sepuh's MR, and I honestly feel like this can be translated properly as "Parameter" and "Pengembalian". Should we do that? (In current MR, I left it as is)

Yes, as discussed over here, https://github.com/reactjs/id.react.dev/discussions/337#discussioncomment-5769320, we agreed to translate them.

> * Should I translate following terms?
>   
>   * "server-side rendering (SSR)" → "Perenderan pada sisi server (server-side rendering, SSR)"
>   * "static site generation (SSG)" → "Pembangunan situs statik (static site generation, SSG)"
>   
>   Currently I've left it as is and treat it as loan word (term?).

Those are very popular phrases recently in the frontend community. I think translating them prematurely might lead to more confusions. Therefore, let's keep them as loan words, but don't forget to italicize them.

> Also note:
> 
> * I noticed that loanwords that have been 'glued' with _imbuhan_ such as ["merender"](https://github.com/reactjs/id.react.dev/pull/351/files#r1179192132) currently don't need to be italicized or separated with `-`, I applied this rule for "render", "unmount", "hydrate", "log".

I disagree. In [PUEBI](https://ivanlanin.github.io/puebi/tanda-baca/tanda-hubung/), we have to italicize them while connecting the prefix and suffix with `-`.
![image](https://user-images.githubusercontent.com/6315466/235482838-41fad48e-a22a-4cd9-9eff-5ff60a776a65.png)

> * I did not translate the error messages in the Troubleshooting part because I don't think error messages in React is localized too. Please let me know if this should actually be translated too.

Yes, please leave the error messages in the Troubleshooting part because that's what the readers will encounter while actually running the code and using React in the real world.

> Thank you so much!

Thank you for your comprehensive considerations and contribution!

2023-05-03 17:15 UTC, r17x requested changes

2023-06-28 18:11 UTC, r17x commented
Hello @chez14, Do you need a help for this PRs?

Thanks

2023-07-01 02:41 UTC, chez14 commented
Hi @r17x,

Ah thank you for reaching back, I'm waiting for more feedback so I can edit them in one go.

Should I just patch this, or... wait for other reviewer first?

Thanks!

2023-07-01 03:34 UTC, resir014 commented
@chez14 You can start working on any suggested changes now. We can come back and review it later.

2023-07-01 13:28 UTC, chez14 commented
Hi @r17x, @resir014, and @zainfathoni,

I have updated the PR as requested. 

Please let me know if you have any feedback or questions. Thank you!

2023-07-01 13:37 UTC, r17x commented on src/content/reference/react-dom/client/createRoot.md
> +`createRoot` memungkinkan Anda untuk membuat sebuah akar untuk menampikan komponen React dalam node DOM pada browser.
Peramban

2023-07-01 13:38 UTC, r17x commented on src/content/reference/react-dom/client/createRoot.md
> +Panggil `createRoot` untuk membuat akar React untuk menampilkan konten di elemen DOM di browser.
Idem https://github.com/reactjs/id.react.dev/pull/514/files#r1248843137

2023-07-02 07:07 UTC, r17x approved these changes

2023-07-02 07:09 UTC, r17x commented
@zainfathoni @resir014 This PRs have been updated yet, need re-review.

2023-07-06 07:00 UTC, r17x commented
@resir014 could you review this PR

2023-07-06 16:49 UTC, resir014 approved these changes

2023-07-06 16:49 UTC, merged