Translated `react: Components > <Profiler>`
reactjs/id.react.dev pull request #515
Opened 2023-04-30 09:16 UTC by rimuhamu

Closes #414 

Translate the `react: Components > <Profiler>` page.
Page URL: https://react.dev/reference/react/Profiler

2023-05-03 12:53 UTC, r17x requested changes

2023-05-03 12:53 UTC, r17x commented on src/content/reference/react/Profiler.md
> +* `onRender`: Sebuah [`onRender` *callback*](#onrender-callback) yang dipanggil oleh React setiap kali komponen dalam pohon yang diprofilkan diperbarui. Menerima informasi tentang apa yang di*render*
```suggestion
* `onRender`: Sebuah [`onRender` *callback*](#onrender-callback) yang dipanggil oleh React setiap kali komponen dalam pohon yang diprofilkan diperbarui. Menerima informasi tentang apa yang di-*render* dan berapa lama waktu yang dibutuhkan.
```

[Referensi](https://github.com/reactjs/id.react.dev/discussions/337#discussioncomment-5772140)

2023-05-03 12:53 UTC, r17x commented on src/content/reference/react/Profiler.md
> +* Pembuatan *profiler* akan menambah waktu komputasi, sehingga **dinonaktifkan dalam *build* produksi secara *default*.** Untuk menggunakan *profiler* dalam produksi, Anda harus mengaktifkan sebuah [
```suggestion
* Pembuatan *profiler* akan menambah waktu komputasi, sehingga **dinonaktifkan dalam *build* produksi secara bawaan.** Untuk menggunakan *profiler* dalam produksi, Anda harus mengaktifkan sebuah [*build* produksi spesial dengan opsi pembuatan *profiler*.](https://fb.me/react-profiling)
```

2023-05-03 12:58 UTC, r17x requested changes

2023-05-03 12:58 UTC, r17x commented on src/content/reference/react/Profiler.md
> +React akan memanggil `onRender` callback Anda dengan informasi tentang apa yang sudah di*render*.
```suggestion
React akan memanggil `onRender` *callback* Anda dengan informasi tentang apa yang sudah di-*render*.
```

Idem https://github.com/reactjs/id.react.dev/pull/515#discussion_r1183645323

2023-05-03 12:58 UTC, r17x commented on src/content/reference/react/Profiler.md
> +* `actualDuration`: Jumlah milidetik yang dihabiskan untuk me*render* `<Profiler>` dan turunannya untuk pembaruan terkini. Ini mengindikasikan seberapa baik *sub*-pohon menggunakan memoisasi (contohn
idem https://github.com/reactjs/id.react.dev/pull/515#discussion_r1183645323

2023-05-03 12:58 UTC, r17x commented on src/content/reference/react/Profiler.md
> +* `startTime`: Stempel waktu numerik untuk mengetahui kapan React mulai me*render* pembaruan terkini.
idem https://github.com/reactjs/id.react.dev/pull/515#discussion_r1183645323

2023-06-04 16:29 UTC, mhaidarhanif commented
@rimuhamu Please fix and resolve this to be approved by @r17x

2023-06-04 21:18 UTC, rimuhamu commented
done, please kindly review @r17x

2023-06-05 03:30 UTC, mhaidarhanif commented
@rimuhamu has resolved the issues, @r17x can check and approve if everything's okay

2023-06-22 03:54 UTC, mazipan approved these changes

2023-06-22 03:55 UTC, mazipan commented
@r17x check the review

2023-06-29 08:13 UTC, r17x approved these changes

2023-06-29 08:15 UTC, merged