translate title for draft PR
reactjs/id.react.dev pull request #531
Opened 2023-05-01 21:28 UTC by doaortu

Closes #392 

## Description

Translate the Separating Events from Effects page.
Page URL: [Separating Events from Effects](https://react.dev/learn/separating-events-from-effects)

2023-05-07 08:34 UTC, r17x requested changes

2023-05-07 08:34 UTC, r17x commented on src/content/learn/separating-events-from-effects.md
> +Event handler hanya akan tereksekusi ketika kita melakukan interaksi tertentu. Berbeda dengan event handler, Effect akan tereksekusi ulang jika nilai yang ada di _dependency array Effect_ berbeda/ber
```suggestion
Event handler hanya akan tereksekusi ketika kita melakukan interaksi tertentu. Berbeda dengan event handler, Effect akan tereksekusi ulang jika nilai yang ada di _dependency array Effect_ berbeda/berubah dari nilai sebelumnya. Kadang kita juga ingin memanfaatkan keduanya: Effect yang tereksekusi ketika beberapa nilai berubah, tetapi tidak pada yang lain. Halaman ini akan mengajari Anda cara melakukannya.
```

Agar konsisten dengan konten translation yang sudah ada, gunakan `*` daripada `_` untuk membuat kata miring (*italic*)/

2023-05-07 08:34 UTC, r17x commented on src/content/learn/separating-events-from-effects.md
> +- Cara membaca nilai props dan state dari Effect menggunakan Effect Event
```suggestion
- Cara membaca nilai *props* dan *state* dari Effect menggunakan Effect Event
```

Jangan lupa dibuat menjadi tulisan miring (*italic*) untuk yang bukan kata dari Bahasa Indonesia.

2023-05-07 10:33 UTC, doaortu commented on src/content/learn/separating-events-from-effects.md
> +Event handler hanya akan tereksekusi ketika kita melakukan interaksi tertentu. Berbeda dengan event handler, Effect akan tereksekusi ulang jika nilai yang ada di _dependency array Effect_ berbeda/ber
oke gan, terima kasih atas review nya.
sebentar saya akan *update* di *commit* selanjutnya

2023-05-07 11:01 UTC, doaortu commented on src/content/learn/separating-events-from-effects.md
> +- Cara membaca nilai props dan state dari Effect menggunakan Effect Event
terimakasih reviewnya, sebelumnya saya mau memastikan gan, untuk istilah Effect, Effect Event itu perlu dibuat miring tidak ya? saya pernah baca kalo istilah kata inggris yang ditulis kapital tidak perlu dibuat miring.
kalo kasusnya disini bagaimana ya?

2023-05-08 14:34 UTC, mazipan commented on src/content/learn/separating-events-from-effects.md
> +## Cara menentukan kapan menggunakan *event handler* atau Effect {/*choosing-between-event-handlers-and-effects*/}
Lebih simpel

```suggestion
## Memilih antara *event handler* atau Effect {/*choosing-between-event-handlers-and-effects*/}
```

2023-05-08 22:22 UTC, doaortu commented on src/content/learn/separating-events-from-effects.md
> +## Cara menentukan kapan menggunakan *event handler* atau Effect {/*choosing-between-event-handlers-and-effects*/}
Terima kasih atas *suggestion*-nya. Sudah saya terapkan pada *commit* di bawah.

2023-05-10 04:39 UTC, mazipan commented on src/content/learn/separating-events-from-effects.md
> +*Event handler* hanya akan tereksekusi ketika kita melakukan interaksi tertentu. Berbeda dengan *event handler*, Effect akan tereksekusi ulang jika nilai yang ada di *dependency array Effect* berbeda
Ini cukup beda sama origin wording nya.

```suggestion
*Event handler* hanya akan dijalankan ulang ketika kita melakukan interaksi yang sama kembali. Berbeda dengan *event handler*, *Effect* akan disinkronisasi ulang jika beberapa nilai yang dibaca,seperti *prop* atau variabel *state*, berbeda dari apa yang ada pada *render* sebelumnya. Terkadang Anda juga ingin mencampur perilaku keduanya: Sebuah *Effect* yang dijalankan ulang menanggapi beberapa nilai tertentu tapi tidak pada yang lainnya. Halaman ini akan mengajari Anda cara melakukannya.
```

2023-05-10 04:39 UTC, mazipan commented on src/content/learn/separating-events-from-effects.md
> +- Cara menentukan kapan menggunakan *event handler* atau Effect
```suggestion
- Cara memilih antara *event handler* dan *Effect*
```

2023-05-10 04:39 UTC, mazipan commented on src/content/learn/separating-events-from-effects.md
> +- Cara menentukan kapan menggunakan *event handler* atau Effect
```suggestion
- Cara memilih antara *event handler* dan *Effect*
```

2023-05-10 04:39 UTC, mazipan commented on src/content/learn/separating-events-from-effects.md
> +- Apa yang dimaksud Effect Event, dan bagaimana cara kita menggunakannya di Effect
```suggestion
- Apa yang dimaksud *Effect Event*, dan bagaimana untuk mengeluarkan dari *Effect* Anda
```

2023-05-10 04:39 UTC, mazipan commented on src/content/learn/separating-events-from-effects.md
> +- Cara membaca nilai *props* dan *state* dari Effect menggunakan Effect Event
```suggestion
- Bagaimana cara membaca nilai *props* dan *state terbaru dari *Effects* menggunakan *Effect Event*
```

2023-05-10 04:39 UTC, mazipan commented on src/content/learn/separating-events-from-effects.md
> +Mari kita mulai dengan merangkum perbedaan antara *event handler* dan Effect.
```suggestion
Pertama, mari kita rangkum perbedaan antara *event handler* dan *Effects*.
```

2023-05-10 04:39 UTC, mazipan commented on src/content/learn/separating-events-from-effects.md
> +Sekarang, bayangkan bahwa kita ingin menerapkan suatu komponen untuk ruang obrolan (*chatroom*). Persyaratan utamanya meliputi:
```suggestion
Bayangkan Anda sedang menerapkan suatu komponen ruang obrolan (*chatroom*). Persyaratan Anda terlihat seperti ini:
```

2023-05-10 04:39 UTC, mazipan commented on src/content/learn/separating-events-from-effects.md
> +1. Komponen harus terhubung secara otomatis ke ruang obrolan yang sudah dipilih.
```suggestion
1. Komponen Anda harus terhubung secara otomatis ke ruang obrolan yang terpilih.
```

2023-05-10 04:39 UTC, mazipan commented on src/content/learn/separating-events-from-effects.md
> +1. Ketika tombol 'Kirim' ditekan, kita harus dapat mengirimkan pesan ke dalam ruang obrolan.
```suggestion
1. Ketika Anda menekan tombol 'Kirim, itu harus mengirimkan pesan ke dalam obrolan.
```

2023-05-10 04:39 UTC, mazipan commented on src/content/learn/separating-events-from-effects.md
> +Setelah kita mengimplementasikan kode untuk kebutuhan tersebut, mungkin akan timbul kebingungan dalam memilih tempat untuk meletakkannya. Apakah kita perlu menggunakan *event handler* atau malah meng
```suggestion
Katakanlah Anda telah mengimplementasikan kode tersebut, tapi Anda tidak yakin dimana meletakannya. Apakah Anda perlu menggunakan *event handler* atau *Effects*? Setiap kali Anda butuh jawaban dari pertanyaan ini, pertimbangkan [*mengapa* kode tersebut perlu dijalankan](/learn/synchronizing-with-effects#what-are-effects-and-how-are-they-different-from-events).
```

2023-05-10 04:40 UTC, mazipan commented
Word per word nya banyak yang miss, pelan-pelan aja terjemahinnya, kadang-kadang kehilangan satu kata, bisa mengubah tujuan utama dari suatu kalimat.

2026-09-10 23:54 UTC, zainfathoni commented
Closing as stale and unmergeable (conflicts with main; review feedback from 2023 was never fully resolved). Please open a new PR from current main if you want to continue the Separating Events from Effects translation.

2026-09-10 23:54 UTC, closed without merging