feat: translate to indonesia in line 90
reactjs/id.react.dev pull request #534
Opened 2023-05-02 07:03 UTC by naufaldi

Closes #425 

## Description

Translate the JavaScript in JSX with Curly Braces  page.
Page URL: [JavaScript in JSX with Curly Braces ](https://id.react.dev/learn/javascript-in-jsx-with-curly-braces)

2023-05-18 07:57 UTC, resir014 requested changes
First pass of review done. Some changes needed @naufaldi:

2023-05-18 07:57 UTC, resir014 commented on src/content/learn/javascript-in-jsx-with-curly-braces.md
> +title: JavaScript di JSX menggunakan Curly Braces
```suggestion
title: JavaScript di JSX menggunakan Kurung Kurawal
```

I think we can translate this term, yes? @mhaidarhanif @zainfathoni

2023-05-18 07:57 UTC, resir014 commented on src/content/learn/javascript-in-jsx-with-curly-braces.md
> +* Bagaimana cara untuk oper *strings* dengan tanda kutip
```suggestion
* Bagaimana cara mengoper *string* dengan tanda kutip
```

Always convert loan words to its singular term.

2023-05-18 07:57 UTC, resir014 commented on src/content/learn/javascript-in-jsx-with-curly-braces.md
> +## Mengoper *strings* dengan tanda kutip {/*passing-strings-with-quotes*/}
```suggestion
## Mengoper string dengan tanda kutip {/*passing-strings-with-quotes*/}
```

- Singular term for loanwords.
- Don't italicise loanwords in headings.

2023-05-18 07:57 UTC, resir014 commented on src/content/learn/javascript-in-jsx-with-curly-braces.md
> +Disini, `"https://i.imgur.com/7vQD0fPs.jpg"` dan `"Gregorio Y. Zara"` sedang dioper sebagai *strings*.
```suggestion
Disini, `"https://i.imgur.com/7vQD0fPs.jpg"` dan `"Gregorio Y. Zara"` sedang dioper sebagai *string*.
```

Idem.

2023-05-18 07:57 UTC, resir014 commented on src/content/learn/javascript-in-jsx-with-curly-braces.md
> +Anda hanya dapat menggunakan kurung keriting (curly braces) dalam dua cara di dalam JSX:
```suggestion
Anda hanya dapat menggunakan kurung kurawal (curly braces) dalam dua cara di dalam JSX:
```

Let's make it consistent with the rest, use "kurung kurawal"

2023-05-18 07:57 UTC, resir014 commented on src/content/learn/javascript-in-jsx-with-curly-braces.md
> +Kode ini mengalami crash dengan pesan galat yang menyatakan `Objects are not valid as a React child`:
```suggestion
Kode ini mengalami *crash* dengan pesan galat yang menyatakan `Objects are not valid as a React child`:
```

Missing italics.

2023-05-18 08:02 UTC, mazipan commented on src/content/learn/javascript-in-jsx-with-curly-braces.md
> +Disini, `"https://i.imgur.com/7vQD0fPs.jpg"` dan `"Gregorio Y. Zara"` sedang dioper sebagai *strings*.
Add Disini -> Di sini

2023-06-04 16:20 UTC, mhaidarhanif commented
@naufaldi need to resolve the requests from @resir014

2023-06-06 11:38 UTC, mazipan commented on src/content/learn/javascript-in-jsx-with-curly-braces.md
> +Selain string, angka, dan ekspresi JavaScript lainnya, Anda bahkan dapat oper objek dalam JSX. Objek juga ditandai dengan kurung kurawal, seperti `{ name: "Hedy Lamarr", inventions: 5 }`. Oleh karena
```suggestion
Selain string, angka, dan ekspresi JavaScript lainnya, Anda bahkan dapat mengoper objek dalam JSX. Objek juga ditandai dengan kurung kurawal, seperti `{ name: "Hedy Lamarr", inventions: 5 }`. Oleh karena itu, untuk mengoper objek JavaScript di JSX, Anda harus membungkus objek tersebut dalam sepasang kurung kurawal lainnya: `person={{ name: "Hedy Lamarr", inventions: 5 }}`.
```

2023-06-11 07:29 UTC, resir014 commented
@naufaldi Hi, any updates? If there are no updates within the next 24 hours, the maintainers will take over this PR.

2023-06-13 02:32 UTC, resir014 approved these changes
All good. Thanks!

2023-06-13 02:58 UTC, merged