docs: translate API Reference -> `react` -> built-in components
reactjs/id.react.dev pull request #555
Opened 2023-05-10 08:10 UTC by aroyan

Closes #412 

## Description

Translate the `Built-in React Components` page.
Page URL: [Built-in React Components](https://react.dev/reference/react/components)

2023-05-22 10:15 UTC, resir014 requested changes
Only one minor change needed. @aroyan

2023-05-22 10:15 UTC, resir014 commented on src/content/reference/react/components.md
> +* [`<Fragment>`](/reference/react/Fragment), sebagai alternatif dapat ditulis menjadi `<>...</>`, memungkinkan Anda untuk mengelompokkan beberapa JSX nodes secara bersamaan.
```suggestion
* [`<Fragment>`](/reference/react/Fragment), sebagai alternatif dapat ditulis menjadi `<>...</>`, memungkinkan Anda untuk mengelompokkan beberapa simpul JSX secara bersamaan.
```

JSX node -> simpul JSX

2023-06-22 03:58 UTC, mazipan approved these changes

2023-06-22 03:58 UTC, mazipan commented
@resir014

2023-06-26 04:49 UTC, resir014 approved these changes

2023-06-26 04:50 UTC, merged