docs: translate Legacy React APIs
reactjs/id.react.dev pull request #557
Opened 2023-05-11 16:15 UTC by renomureza

Closes #545

## Description

Translate the Legacy React APIs page.
Page URL:  https://id.react.dev/reference/react/legacy

2023-05-18 08:08 UTC, resir014 requested changes
One minor change. @renomureza

2023-05-18 08:08 UTC, resir014 commented on src/content/reference/react/legacy.md
> +* [`Children`](/reference/react/Children) memungkinakn Anda memanipulasi dan mengubah JSX yang diterima sebagai *prop* `children`. [Lihat alternatif.](/reference/react/Children#alternatives)
```suggestion
* [`Children`](/reference/react/Children) memungkinkan Anda memanipulasi dan mengubah JSX yang diterima sebagai *prop* `children`. [Lihat alternatif.](/reference/react/Children#alternatives)
```

typo

2023-05-18 08:24 UTC, mazipan commented on src/content/reference/react/legacy.md
> +API ini akan dihapus di versi utama React yang akan datang.
Plural.
Major -> Mayor
```suggestion
API-API ini akan dihapus di versi mayor React yang akan datang.
```

2023-05-18 08:33 UTC, mazipan approved these changes

2023-05-18 08:34 UTC, mazipan commented
This is quite small, let's ship this @resir014, need your approval

2023-05-18 08:43 UTC, renomureza commented
Thanks for the correction, mas @resir014 @mazipan.

2023-05-19 01:54 UTC, resir014 approved these changes

2023-05-19 01:54 UTC, merged