docs: translation for `Component(class)`
reactjs/id.react.dev pull request #571
Opened 2023-05-30 01:50 UTC by aroyan

Closes 

## Description

Translate the  page.
Page URL:

2024-03-28 23:54 UTC, aroyan commented
Please review @mhaidarhanif @zainfathoni @mazipan @resir014

2024-03-29 12:48 UTC, mhaidarhanif requested changes
Because it seems there are some typos, please check again.

Karena sepertinya masih ada beberapa _typo_, silakan dicek lagi dahulu.

2024-03-29 12:48 UTC, mhaidarhanif commented on src/content/reference/react/Component.md
> +Kami merekomendasikan mendefinisikan komponen sebagai fungsi dari pada kelas. [Lihat bagaimana cara migrasi.](#alternatives)
```suggestion
Kami merekomendasikan mendefinisikan komponen sebagai fungsi daripada kelas. [Lihat bagaimana cara migrasi.](#alternatives)
```

https://kbbi.web.id/daripada

2024-03-29 12:48 UTC, mhaidarhanif commented on src/content/reference/react/Component.md
> +`Component` adalah kelas dasar untuk komponen React yang didefinisikan segabai [JavaScript classes.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) Kelas komponen masih di
```suggestion
`Component` adalah kelas dasar untuk komponen React yang didefinisikan sebagai [JavaScript classes.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) Kelas komponen masih didukung oleh React, tetapi kami tidak merekomendasikan untuk menggunakannya di kode baru.
```

2024-06-23 01:54 UTC, resir014 commented on src/content/reference/react/Component.md
> +API ini akan dihapus pada versi utama React di masa depan. [Gunakan `createRef` sebagai gantinya.](/reference/react/createRef)
```suggestion
API ini akan dihapus pada versi mayor React di masa depan. [Gunakan `createRef` sebagai gantinya.](/reference/react/createRef)
```

`versi utama` -> `versi mayor`

2024-06-23 01:54 UTC, resir014 commented on src/content/reference/react/Component.md
> +Jika komponent Anda tidak disinkronkan dengan sistem eksternal apapun, [Anda mungkin tidak membutuhkan sebuah *Effect*.](/learn/you-might-not-need-an-effect)
```suggestion
Jika komponen Anda tidak disinkronkan dengan sistem eksternal apapun, [Anda mungkin tidak membutuhkan sebuah *Effect*.](/learn/you-might-not-need-an-effect)
```

komponent -> komponen

2024-06-23 02:02 UTC, resir014 commented on src/content/reference/react/Component.md
>  #### Parameters {/*setstate-parameters*/}
```suggestion
#### Parameter {/*setstate-parameters*/}
```

2024-06-23 02:02 UTC, resir014 commented on src/content/reference/react/Component.md
>  #### Parameters {/*shouldcomponentupdate-parameters*/}
```suggestion
#### Parameter {/*shouldcomponentupdate-parameters*/}
```

2024-06-23 02:02 UTC, resir014 commented on src/content/reference/react/Component.md
>  #### Parameters {/*constructor-parameters*/}
```suggestion
#### Parameter {/*constructor-parameters*/}
```

2024-06-23 02:02 UTC, resir014 commented on src/content/reference/react/Component.md
>  #### Parameters {/*unsafe_componentwillmount-parameters*/}
```suggestion
#### Parameter {/*unsafe_componentwillmount-parameters*/}
```

2024-06-23 02:02 UTC, resir014 commented on src/content/reference/react/Component.md
>  #### Parameters {/*unsafe_componentwillreceiveprops-parameters*/}
```suggestion
#### Parameter {/*unsafe_componentwillreceiveprops-parameters*/}
```

2024-06-23 02:02 UTC, resir014 commented on src/content/reference/react/Component.md
>  #### Parameters {/*unsafe_componentwillupdate-parameters*/}
```suggestion
#### Parameter {/*unsafe_componentwillupdate-parameters*/}
```

2024-06-23 02:02 UTC, resir014 commented on src/content/reference/react/Component.md
>  #### Parameters {/*static-getderivedstatefromerror-parameters*/}
```suggestion
#### Parameter {/*static-getderivedstatefromerror-parameters*/}
```

2024-06-23 02:02 UTC, resir014 commented on src/content/reference/react/Component.md
>  #### Parameters {/*static-getderivedstatefromprops-parameters*/}
```suggestion
#### Parameter {/*static-getderivedstatefromprops-parameters*/}
```

2024-06-23 06:20 UTC, resir014 approved these changes

2024-06-23 06:20 UTC, merged

2024-06-23 06:35 UTC, aroyan commented
Terima kasih bang sudah dibantu fix @resir014