docs: translate Suspense page
reactjs/id.react.dev pull request #601
Opened 2023-07-30 15:21 UTC by chez14

Fixes #416 and closes #523

## Description

This PR adds translation to "Suspense" page, continuing @maulanasdqn effort.

Translate the Suspense page.
Page URL:
- 🌍: https://react.dev/reference/react/Suspense
- 🇮🇩: https://id.react.dev/reference/react/Suspense

2023-08-06 07:50 UTC, chez14 commented
I'm having hard time translating these terms:
- Suspend → Ditangguhkan?
- Fallback → *fallback*

For now, I'll take notes on all of these terms and will consult while submitting this PR for review.

2023-08-21 08:12 UTC, resir014 commented
> Suspend → Ditangguhkan?
> Fallback → fallback
> Boundary → Batasan
> Lazy-loading → Lazy-load

Yep, all these should be correct. @chez14

2023-08-21 22:15 UTC, chez14 commented
I got quite busy past few weeks, I'll target to finish this MR/PR by this week.

2023-08-26 11:26 UTC, chez14 commented
Hi @resir014 and @zainfathoni,

This PR is ready for review, please let me know if you have any feedback.

Thank you!

---

Hi @maulanasdqn,

Thank you for the initial translation work. As most of the work were done by you, I think it's fair to ask for your feedback too when you're able to review the PR haha.

Thank you!

2023-09-10 09:05 UTC, resir014 commented
@chez14 Sorry for the delay, I can help in tagging the reviewers for now. @mhaidarhanif @zainfathoni @mazipan @r17x

2023-09-10 09:25 UTC, mhaidarhanif requested changes
First review with suggestion

2023-09-10 09:25 UTC, mhaidarhanif commented on src/content/reference/react/Suspense.md
> +* `fallback`: UI alternatif untuk di-*render* menggantikan UI yang sebenarnya jika belum selesai dimuat. Simpul React apapun yang valid akan diterima, meskipun dalam praktiknya, *fallback* adalah tam
To keep in line with the original sentence.

```suggestion
* `fallback`: UI alternatif untuk di-*render* menggantikan UI yang sebenarnya jika belum selesai dimuat. Simpul React apapun yang valid akan diterima, meskipun dalam praktiknya, *fallback* adalah tampilan pengganti yang ringan, Suspense akan secara otomatis beralih ke `fallback` ketika `children` ditangguhkan, dan kembali ke `children` ketika datanya sudah siap. Jika `fallback` ditangguhkan sewaktu melakukan *rendering*, itu akan mengaktifkan batasan Suspense dari induk terdekat.
```

2023-09-13 09:46 UTC, mhaidarhanif requested changes
Some more suggestions.

2023-09-13 09:46 UTC, mhaidarhanif commented on src/content/reference/react/Suspense.md
> +Pada contoh di bawah ini, Komponen `Albums` *ditangguhkan* saat mengambil daftar album. Hingga komponen tersebut siap untuk di-*render*, React mengganti batasan Suspense terdekat di atas untuk menunj
Small fix and following the original sentence.

```suggestion
Pada contoh di bawah ini, komponen `Albums` *ditangguhkan* saat mengambil daftar album. Hingga komponen tersebut siap untuk di-*render*, React mengganti batasan Suspense terdekat di atas untuk menunjukkan *fallback*--komponen `Loading` Anda. Kemudian, saat data termuat, React menyembunyikan *fallback* `Loading` dan me-*render* komponen `Albums` dengan data.
```

2023-09-13 09:46 UTC, mhaidarhanif commented on src/content/reference/react/Suspense.md
> +  // Tambahkan penundaan palsu agar penantian data lebih terasa.
Small suggestion.

```suggestion
  // Tambahkan penundaan palsu agar penantian data lebih jelas.
```

<img width="641" alt="image" src="https://github.com/reactjs/id.react.dev/assets/235584/b9a6ddcd-d95c-40c2-ad75-c400b6fa9b21">

2023-09-13 09:46 UTC, mhaidarhanif commented on src/content/reference/react/Suspense.md
> +**Hanya sumber data yang mendukung Suspense yang akan mengaktifkan komponen Suspense.** Sumber data tersebut antara lain:
Small improvement.

```suggestion
**Hanya sumber data yang mendukung Suspense yang akan mengaktifkan komponen Suspense.** Yaitu:
```

2023-09-13 09:46 UTC, mhaidarhanif commented on src/content/reference/react/Suspense.md
> +- Pe-*lazy-load*-an kode komponen dengan [`lazy`](/reference/react/lazy)
Small suggestion to improve reading.

```suggestion
- Kode komponen *lazy-loading* dengan [`lazy`](/reference/react/lazy)
```

2023-09-13 09:46 UTC, mhaidarhanif commented on src/content/reference/react/Suspense.md
> +Pengambilan data yang mendukung Suspense tanpa menggunakan *framework* yang mendukung fitur tersebut, belum didukung. Persyaratan untuk mengimplementasikan sumber data yang mendukung Suspense masih b
Small fix.

opinionated = dogmatis

```suggestion
Pengambilan data yang mendukung Suspense tanpa menggunakan *framework* dogmatis belum didukung. Persyaratan untuk mengimplementasikan sumber data yang mendukung Suspense masih belum stabil dan belum terdokumentasi. API resmi untuk mengintegrasikan sumber data dengan Suspense akan dirilis pada versi React yang akan datang.
```

<img width="633" alt="image" src="https://github.com/reactjs/id.react.dev/assets/235584/d28d758d-fb5b-44d9-8d94-e4cc730b87bf">

2023-09-13 09:46 UTC, mhaidarhanif commented on src/content/reference/react/Suspense.md
> +Pada contoh di bawah ini, baik `Biography` dan `Album` mengambil beberapa data. Namun, karena mereka dikelompokkan di bawah satu batasan Suspense, komponen-komponen ini akan selalu "muncul" bersamaan
To follow with the original sentence.

```suggestion
Pada contoh di bawah ini, baik `Biography` dan `Album` mengambil beberapa data. Namun, karena mereka dikelompokkan di bawah satu batasan Suspense, komponen-komponen ini akan selalu "muncul" bersama-sama pada waktu yang sama.
```

2023-09-13 09:46 UTC, mhaidarhanif commented on src/content/reference/react/Suspense.md
> +    throw Error('Chat seharusnya hanya dirender pada klien.');
```suggestion
    throw Error('Chat seharusnya hanya di-render di klien.');
```

2023-09-13 09:48 UTC, mhaidarhanif commented
@chez14 Just reviewed with some more suggestions.

cc @resir014 @zainfathoni @r17x @mazipan

2023-10-12 09:53 UTC, resir014 commented
Hi, any updates to this? @chez14

2023-10-17 20:13 UTC, chez14 commented
Ah sorry, i missed this notification. I've been quite busy with office work lately, I'll try to update this PR by this week.

Thank you!

2023-11-05 04:54 UTC, resir014 commented
@chez14 Hi, are you still able to work on this? If you're unable to work on this within the next 3-5 days, we can take over your PRs.

2024-01-13 12:20 UTC, maulanasdqn commented
@resir014r can i continue this work? cc @chez14

2024-01-14 02:50 UTC, resir014 commented
Yes, feel free to pick up this PR! @maulanasdqn

2024-04-08 02:22 UTC, resir014 commented
Picking this up again since we need to get the remaining pages translated since we have some other new pages to translate.

2024-04-08 02:22 UTC, resir014 approved these changes

2024-04-08 03:48 UTC, merged