docs: translate 'react calls component and hooks'
reactjs/id.react.dev pull request #660
Opened 2024-04-09 14:48 UTC by FelixFern

Closes #653 

## Description

Translate the reference/rules/react-calls-components-and-hooks page.
Page URL: https://id.react.dev/reference/rules/react-calls-components-and-hooks

2024-04-10 15:15 UTC, r17x requested changes
* Use `*` instead `_` for Italic
* Use Italic style text when english in bahasa (e.g: `*rendering*`)

2024-04-10 15:15 UTC, r17x commented on src/content/reference/rules/react-calls-components-and-hooks.md
> +Jika sebuah komponen mengandung Hooks, sangat mudah untuk melanggar [Aturan dari Hooks](/reference/rules/rules-of-hooks) saat komponen secara langsung dipanggil dalam sebuah loop ataupun secara kondi
```suggestion
Jika sebuah komponen mengandung *Hooks*, sangat mudah untuk melanggar [Aturan dari Hooks](/reference/rules/rules-of-hooks) saat komponen secara langsung dipanggil dalam sebuah perulangan ataupun secara kondisional.
```

2024-04-10 15:15 UTC, r17x commented on src/content/reference/rules/react-calls-components-and-hooks.md
> +React bertanggung jawab untuk me-*render* komponen dan Hooks saat diperlukan untuk mengoptimisasi pengalaman pengguna. Ini bersifat deklaratif: Anda memberi tahu React apa yang harus di-*render* dala
```suggestion
React bertanggung jawab untuk me-*render* komponen dan *Hooks* saat diperlukan untuk mengoptimisasi pengalaman pengguna. Ini bersifat deklaratif: Anda memberi tahu React apa yang harus di-*render* dalam logika komponen Anda, dan React akan mencari cara terbaik untuk menampilkannya kepada pengguna Anda.
```

2024-04-10 15:15 UTC, r17x commented on src/content/reference/rules/react-calls-components-and-hooks.md
> +Membiarkan React melakukan orkestrasi rendering juga memungkinkan sejumlah manfaat:
```suggestion
Membiarkan React melakukan orkestrasi *rendering* juga memungkinkan sejumlah manfaat:
```

2024-04-11 11:04 UTC, r17x requested changes
* Mostly need to Italic word in Bahasa (e.g: `*Hooks*, me-*render*`)
* Use `*` instead of `_` for italic

2024-04-11 14:54 UTC, FelixFern commented on src/content/reference/rules/react-calls-components-and-hooks.md
> +Dengan cara ini, `<Button />` menjadi lebih mudah untuk dipahami dan didebug. Saat Hooks digunakan dengan cara yang dinamis, komplesitas dari aplikasi akan meningkat secara signifikan dan menghambat
ok noted mas

2024-04-11 14:54 UTC, FelixFern commented on src/content/reference/rules/react-calls-components-and-hooks.md
> +Hooks juga seharusnya tidak digunakan secara dinamis: sebagai contoh, gunakanlah *dependency injection* pada sebuah komponen dengan cara mengopernya kedalam Hook sebaga sebuah nilai:
ok noted mas

2024-04-11 14:54 UTC, FelixFern commented on src/content/reference/rules/react-calls-components-and-hooks.md
> +Hooks seharusnya tidak dapat dimutasi dan tidak dilakukan mutasi. Melainkan memutasi Hook secara dinamis, buatlah sebuah bentuk statis dari Hook tersebut dengan fungsionalitas yang diinginkan.
ok noted mas

2024-04-11 14:54 UTC, FelixFern commented on src/content/reference/rules/react-calls-components-and-hooks.md
> +Sebuah Hooks sebagainya selalu se-"statis" mungkin. Berarti anda seharusnya tidak melakukan mutasi secara dinamis pada Hooks. Sebagai contoh, artinya anda tidak seharusnya menulis sebuah Hooks dengan
ok noted mas

2024-04-11 14:55 UTC, FelixFern commented on src/content/reference/rules/react-calls-components-and-hooks.md
> +Hooks memungkinkan anda untuk menambahkan sebuah komponen dalam fitur React. Hooks seharusnya harus selalu dipanggil sebagai sebuah fungsi, dan tidak dioper sebagai sebuah nilai. Hal ini memungkinkan
ok noted mas

2024-04-12 20:29 UTC, r17x approved these changes

2024-04-13 17:45 UTC, r17x commented
Re:check @resir014

2024-04-28 16:33 UTC, resir014 reviewed
Minor non-blocking change.

2024-04-28 16:33 UTC, resir014 commented on src/content/reference/rules/react-calls-components-and-hooks.md
>  </Intro>
```suggestion
</Intro>
```
Remove extra line here.

2024-04-28 16:38 UTC, resir014 approved these changes

2024-04-28 16:38 UTC, merged