docs: translate 'Rules of React'
reactjs/id.react.dev pull request #661
Opened 2024-04-09 15:51 UTC by ceavinrufus

Closes #651

## Description

Translate the Rules of React page.
Page URL: [id.react.dev/reference/rules](https://id.react.dev/reference/rules)

2024-04-09 17:49 UTC, r17x commented
Sorry @ceavinrufus it duplicated with @resir014 PR https://github.com/reactjs/id.react.dev/pull/657

2024-04-10 06:22 UTC, r17x requested changes

2024-04-10 06:22 UTC, r17x commented on src/content/reference/rules/index.md
> +title: Aturan React
```suggestion
title: Peraturan React
```

2024-04-10 06:22 UTC, r17x commented on src/content/reference/rules/index.md
> +Bagian ini menjelaskan aturan yang perlu Anda ikuti untuk menulis kode React yang idiomatis. Menulis kode React yang idiomatis dapat membantu Anda menulis aplikasi yang terorganisisasi dengan baik, a
Use asterisk `*` instead underscore `_`
```suggestion
Bagian ini menjelaskan aturan yang perlu Anda ikuti untuk menulis kode React yang idiomatis. Menulis kode React yang idiomatis dapat membantu Anda menulis aplikasi yang terorganisisasi dengan baik, aman, dan dapat disusun. Hal ini membuat aplikasi Anda lebih tahan terhadap perubahan dan memudahkan bekerja dengan pengembang, pustaka (*library*), dan alat lain.
```

2024-04-10 06:22 UTC, r17x commented on src/content/reference/rules/index.md
> -These rules are known as the **Rules of React**. They are rules – and not just guidelines – in the sense that if they are broken, your app likely has bugs. Your code also becomes unidiomatic and hard
Use asterisk * instead underscore _

2024-04-10 06:22 UTC, r17x commented on src/content/reference/rules/index.md
> +Kami sangat merekomendasikan penggunaan [Strict Mode](/reference/react/StrictMode) bersama dengan [_plugin_ ESLint](https://www.npmjs.com/package/eslint-plugin-react-hooks) untuk React, untuk membant
* Use asterisk * instead underscore _
* Use asterisk * in "english" terms (e.g: codebase) or use bahasa `basis kode`

2024-04-10 06:22 UTC, r17x commented on src/content/reference/rules/index.md
> +## Komponen dan _Hooks_ harus murni {/*components-and-hooks-must-be-pure*/}
Use asterisk * instead underscore _

2024-04-10 06:22 UTC, r17x commented on src/content/reference/rules/index.md
> +[Kemurnian dalam Komponen dan _Hooks_](/reference/rules/components-and-hooks-must-be-pure) adalah aturan utama React yang membuat aplikasi Anda dapat diprediksi, mudah di-_debug_, dan memungkinkan Re
Use asterisk * instead underscore _

2024-04-10 06:22 UTC, r17x commented on src/content/reference/rules/index.md
> +* [Nilai menjadi _immutable_ setelah dioper ke JSX](/reference/rules/components-and-hooks-must-be-pure#values-are-immutable-after-being-passed-to-jsx) – Jangan ubah nilai setelah digunakan di JSX. Pi
Use asterisk * instead underscore _

2024-04-10 06:22 UTC, r17x commented on src/content/reference/rules/index.md
> +* [Panggil _Hooks_ hanya dari fungsi React](/reference/rules/rules-of-hooks#only-call-hooks-from-react-functions) – Jangan panggil _Hooks_ dari fungsi JavaScript biasa.
* Use asterisk * instead underscore _
* Use asterisk * in "english" terms (e.g: codebase) or use bahasa basis kode

2024-04-10 06:41 UTC, ceavinrufus commented
Could you kindly review my code again, please? @r17x

2024-04-10 16:51 UTC, r17x requested changes

2024-04-10 16:51 UTC, r17x commented on src/content/reference/rules/index.md
> +Meskipun *Hooks* ditulis menggunakan fungsi JavaScript, mereka memiliki fungsi khusus sebagai logika antarmuka yang dapat digunakan kembali. Namun, ada batasan terkait saat Anda bisa menggunakan Hook
```suggestion
Meskipun *Hooks* ditulis menggunakan fungsi JavaScript, mereka memiliki fungsi khusus sebagai logika antarmuka yang dapat digunakan kembali. Namun, ada batasan terkait saat Anda bisa menggunakan *Hook*. Anda perlu mematuhi [Peraturan *Hooks*](/reference/rules/rules-of-hooks) saat menggunakannya.
```

2024-04-10 19:27 UTC, r17x approved these changes

2024-04-12 16:50 UTC, resir014 approved these changes

2024-04-12 16:50 UTC, merged