[WIP] docs: translate understanding your ui as a tree
reactjs/id.react.dev pull request #662
Opened 2024-04-10 16:46 UTC by r17x

Closes 

## Description

Translate the  page.
Page URL:

2024-04-13 00:32 UTC, resir014 commented
@r17x Don't forget to also update the corresponding sidebar in `sidebarLearn.json`:
https://github.com/reactjs/id.react.dev/blob/main/src/sidebarLearn.json#L90-L93

2024-04-13 17:46 UTC, r17x commented
Thank you for remind me, I will update @resir014

2024-04-17 09:12 UTC, zainfathoni requested changes

2024-04-17 09:12 UTC, zainfathoni commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +<Diagram name="preserving_state_dom_tree" height={193} width={864} alt="Diagram dengan tiga bagian yang disusun secara horizontal. Pada bagian pertama, terdapat tiga persegi panjang yang ditumpuk sec
```suggestion
<Diagram name="preserving_state_dom_tree" height={193} width={864} alt="Diagram dengan tiga bagian yang disusun secara horizontal. Pada bagian pertama, terdapat tiga persegi panjang yang ditumpuk secara vertikal, dengan label 'Komponen A', 'Komponen B', dan 'Komponen C'. Transisi ke panel berikutnya adalah sebuah panah dengan logo React di bagian atas yang berlabel 'React'. Bagian tengah berisi sebuah pohon komponen, dengan akar berlabel 'A' dan dua komponen anak berlabel 'B' dan 'C'. Bagian selanjutnya ditransisikan lagi menggunakan panah dengan logo React di bagian atas berlabel 'React DOM'. Bagian ketiga dan terakhir adalah *wireframe* dari sebuah peramban, yang berisi sebuah pohon dengan 8 *node*, yang hanya memiliki sebuah bagian yang disorot (mengindikasikan subpohon dari bagian tengah).">
```

2024-04-17 09:12 UTC, zainfathoni commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +, kita memiliki konsep komponen induk dan anak, di mana setiap komponen induk dapat menjadi anak dari komponen lain.
```suggestion
Fitur utama dari komponen adalah kemampuan untuk menyusun komponen dari komponen lain. Saat kita [menyusun komponen](/learn/your-first-component#nesting-and-organizing-components), kita memiliki konsep komponen induk dan anak, di mana setiap komponen induk dapat menjadi anak dari komponen lain.
```
Keep the link intact.

2024-04-17 10:41 UTC, zainfathoni requested changes

2024-04-17 10:41 UTC, zainfathoni commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +">
```suggestion
<Diagram name="render_tree" height={250} width={500} alt="Graf pohon dengan lima simpul. Tiap simpul merepresentasikan sebuah komponen. Akar dari pohon ini adalah App, dengan dua anak panah yang memanjang dari akar tersebut ke 'InspirationGenerator' dan 'FancyText'. Panah-panah tersebut diberi label dengan kata 'render'. Node 'InspirationGenerator' juga memiliki dua anak panah yang mengarah ke node 'FancyText' dan 'Copyright'.">
```

2024-04-17 10:41 UTC, zainfathoni commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +{/*where-are-the-html-elements-in-the-render-tree*/}
```suggestion
#### Di mana letak dari tag HTML dalam pohon *render*? {/*where-are-the-html-elements-in-the-render-tree*/}
```

2024-04-22 18:28 UTC, merged