docs: translate `Components and Hooks must be pure`
reactjs/id.react.dev pull request #666
Opened 2024-04-29 06:25 UTC by FelixFern

Closes #652

## Description

Translate the reference/rules/components-and-hooks-must-be-pure
Page URL: https://id.react.dev/reference/rules/components-and-hooks-must-be-pure

2024-04-29 09:49 UTC, FelixFern commented
ready for review @r17x @resir014

2024-04-30 02:47 UTC, resir014 requested changes
One minor fix. @FelixFern

2024-04-30 02:47 UTC, resir014 commented on src/content/reference/rules/components-and-hooks-must-be-pure.md
> +pe-*renderan* mengacu pada perhitungan seperti apa tampilan UI anda nantinya. Setelah me-*render*, [Efek](/reference/react/useEffect) di *flush* (artinya mereka akan dijalankan hingga tidak ada lagi
```suggestion
pe-*renderan* mengacu pada perhitungan seperti apa tampilan UI anda nantinya. Setelah me-*render*, [*Effect*](/reference/react/useEffect) di *flush* (artinya mereka akan dijalankan hingga tidak ada lagi yang tersisa) dan dapat memperbarui kalkulasi jika *Effect* berdampak pada *layout*. React akan mengambil kalkulasi ini dan membandingkannya dengan kalkulasi yang digunakannya pada versi sebelumnya dari UI anda, lalu *commits* hanya perubahan minim yang diperlukan ke [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model) (apa yang sebenarnya pengguna lihat) untuk menyesuaikan dengan versi terbaru.
```

Keep *Effect* (as in React's Effects from `useEffect`) untranslated, as opposed to "efek samping" (the programming concept of side effects).

([Reference](https://id.react.dev/learn/synchronizing-with-effects#what-are-effects-and-how-are-they-different-from-events))

2024-04-30 02:47 UTC, resir014 commented on src/content/reference/rules/components-and-hooks-must-be-pure.md
> +    // code ini berada didalam sebuah Efek, sehingga hanya akan jalan saat setelah proses render
```suggestion
    // kode ini berada didalam sebuah Effect, sehingga hanya akan jalan saat setelah proses render
```

Idem.

2024-04-30 02:47 UTC, resir014 commented on src/content/reference/rules/components-and-hooks-must-be-pure.md
> +Efek samping biasanya ditulis di dalam [*event handler*](/learn/responing-to-events) atau Efek. Tetapi tidak pernah selama *render*.
```suggestion
Efek samping biasanya ditulis di dalam [*event handler*](/learn/responing-to-events) atau *Effect*. Tetapi tidak pernah selama *render*.
```

Idem.

2024-04-30 02:47 UTC, resir014 commented on src/content/reference/rules/components-and-hooks-must-be-pure.md
> +Hal ini bukan berarti anda tidak seharusnya menggunakan fungsi idemponen seperti `new Date()` *sama sekali* - anda hanya perlu untuk menghindarinya [saat *render*](#how-does-react-run-your-code), Dal
```suggestion
Hal ini bukan berarti anda tidak seharusnya menggunakan fungsi idemponen seperti `new Date()` *sama sekali* - anda hanya perlu untuk menghindarinya [saat *render*](#how-does-react-run-your-code), Dalam kasus ini, kita bisa *menyinkronkan* tanggal terbaru ke komponen ini dengan [*Effect*](/reference/react/useEffect):
```

2024-04-30 02:47 UTC, resir014 commented on src/content/reference/rules/components-and-hooks-must-be-pure.md
> +Dengan membungkus pemanggilan `new Date()` yang tidak idempoten di dalam sebuah Efek, ini akan memindahkan kalkulasi tersebut [di luar pe-*render*-an](#how-does-react-run-your-code).
```suggestion
Dengan membungkus pemanggilan `new Date()` yang tidak idempoten di dalam sebuah *Effect*, ini akan memindahkan kalkulasi tersebut [di luar pe-*render*-an](#how-does-react-run-your-code).
```

2024-04-30 02:47 UTC, resir014 commented on src/content/reference/rules/components-and-hooks-must-be-pure.md
> +Efek samping adalah istilah yang lebih luas dari Efek. Efek secara khusus merujuk pada kode yang dibungkus dengan `useEffect`, sedangkan efek samping adalah istilah umum untuk kode yang memiliki efek
```suggestion
Efek samping adalah istilah yang lebih luas dari *Effect*. *Effect* secara khusus merujuk pada kode yang dibungkus dengan `useEffect`, sedangkan efek samping adalah istilah umum untuk kode yang memiliki efek yang dapat diamati selain dari hasil utamanya yaitu mengembalikan sebuah nilai kepada pemanggil.
```

2024-04-30 19:16 UTC, r17x approved these changes

2024-04-30 19:20 UTC, r17x commented on src/content/reference/rules/components-and-hooks-must-be-pure.md
> +Ketika Anda menggunakan JSX dalam sebuah ekspresi, React mungkin akan mengevaluasi JSX sebelum komponen selesai di-*render*. Ini berarti bahwa mengubah nilai setelah nilai tersebut dioper ke JSX dapa
```suggestion
Ketika Anda menggunakan JSX dalam sebuah ekspresi, React mungkin akan mengevaluasi JSX sebelum komponen selesai di-*render*. Ini berarti bahwa mengubah nilai setelah nilai tersebut dioper ke JSX dapat menyebabkan UI yang sudah usang, Karena React tidak akan tahu untuk memperbarui keluaran komponen.
```

2024-04-30 19:21 UTC, r17x requested changes
Minor

Dengan menggunakan kata "sudah usang" lebih dekat dengan konteks dari "outdates UIs".

2024-05-01 16:42 UTC, resir014 approved these changes

2024-05-01 16:46 UTC, resir014 commented on src/content/reference/rules/components-and-hooks-must-be-pure.md
> +Ketika Anda menggunakan JSX dalam sebuah ekspresi, React mungkin akan mengevaluasi JSX sebelum komponen selesai di-*render*. Ini berarti bahwa mengubah nilai setelah nilai tersebut dioper ke JSX dapa
```suggestion
Ketika Anda menggunakan JSX dalam sebuah ekspresi, React mungkin akan mengevaluasi JSX sebelum komponen selesai di-*render*. Ini berarti bahwa mengubah nilai setelah nilai tersebut dioper ke JSX dapat menyebabkan UI yang sudah usang, karena React tidak akan tahu untuk memperbarui keluaran komponen.
```

capitalisation

2024-05-02 05:47 UTC, merged