docs: translate Using TypeScript
reactjs/id.react.dev pull request #674
Opened 2024-06-20 10:47 UTC by resir014

Closes #658

## Description

Translate the Using TypeScript page.
Page URL:

2024-06-20 12:58 UTC, r17x approved these changes

2024-06-20 14:17 UTC, mhaidarhanif requested changes
Typo

2024-06-20 14:17 UTC, mhaidarhanif commented on src/content/learn/typescript.md
> +### *Event* DP< {/*typing-dom-events*/}
```suggestion
### *Event* DOM {/*typing-dom-events*/}
```

2024-06-21 09:13 UTC, mhaidarhanif approved these changes
All good

2024-06-21 09:14 UTC, merged