`title` component translation
reactjs/id.react.dev pull request #704
Opened 2024-06-27 07:49 UTC by aroyan

Closes  #690  

## Description

Translate the `<title>` page.
Page URL: https://id.react.dev/reference/react-dom/components/title

2024-07-12 00:00 UTC, resir014 reviewed
One minor change, please check! @aroyan

2024-07-12 00:00 UTC, resir014 commented on src/content/reference/react-dom/components/title.md
> +Ekstensi React untuk `<title>` saat ini hanya tersedia di saluran canary dan eksperimental React. Pada rilis stabil React, `<title>` hanya berfungsi sebagai [komponen HTML bawaan peramban](https://re
```suggestion
Ekstensi React untuk `<title>` saat ini hanya tersedia di kanal *canary* dan eksperimental React. Pada rilis stabil React, `<title>` hanya berfungsi sebagai [komponen HTML bawaan peramban](https://react.dev/reference/react-dom/components#all-html-components). Pelajari lebih lanjut tentang [saluran rilis React di sini](/community/versioning-policy#all-release-channels).
```

saluran -> kanal

2024-07-12 01:18 UTC, aroyan commented
> One minor change, please check! @aroyan

updated, thanks

2024-07-22 13:05 UTC, resir014 commented
> for this link title, should this updated to "kanal" too?

@aroyan yes.

2024-07-22 14:31 UTC, r17x requested changes
use `*` instead of `_` for _italic_

2024-07-31 04:29 UTC, r17x approved these changes

2024-07-31 07:26 UTC, merged