docs: translate page `prefetchDNS`
reactjs/id.react.dev pull request #716
Opened 2024-07-14 01:57 UTC by andriawan

close #692

Closes 

## Description

Translate the  page.
Page URL:

2024-07-19 12:57 UTC, andriawan commented
ready to be reviewed @resir014

2024-07-20 10:06 UTC, r17x requested changes

2024-07-20 10:06 UTC, r17x commented on src/content/reference/react-dom/prefetchDNS.md
> +Panggil `prefetchDNS` di dalam event handler sebelum bertransisi ke halaman atau state yang membutuhkan sumber daya eksternal. Hal ini akan memulai proses lebih awal dibandingkan jika Anda memanggiln
```suggestion
Panggil `prefetchDNS` di dalam *event handler* sebelum bertransisi ke halaman atau *state*yang membutuhkan sumber daya eksternal. Hal ini akan memulai proses lebih awal dibandingkan jika Anda memanggilnya saat merender halaman atau *state* baru.
```

2024-07-20 10:06 UTC, r17x commented on src/content/reference/react-dom/prefetchDNS.md
> +Panggil `prefetchDNS` saat merender komponen jika Anda mengetahui bahwa anak komponen akan memuat sumber daya eksternal dari host tersebut.
```suggestion
Panggil `prefetchDNS` saat me-*render* komponen jika Anda mengetahui bahwa anak komponen akan memuat sumber daya eksternal dari host tersebut.
```

2024-07-20 10:06 UTC, r17x commented on src/content/reference/react-dom/prefetchDNS.md
> +Panggil `prefetchDNS` saat merender komponen jika Anda mengetahui bahwa anak komponen akan memuat sumber daya eksternal dari host tersebut.
```suggestion
Panggil `prefetchDNS` saat me-*render* komponen jika Anda mengetahui bahwa anak komponen akan memuat sumber daya eksternal dari host tersebut.
```

2024-07-20 10:06 UTC, r17x commented on src/content/reference/react-dom/prefetchDNS.md
> +* Dalam rendering sisi server atau saat merender Komponen Server, `prefetchDNS` hanya memiliki efek jika Anda memanggilnya saat merender komponen atau dalam konteks asinkronisasi yang berasal dari re
```suggestion
* Dalam rendering sisi server atau saat me-*render* Komponen Server, `prefetchDNS` hanya memiliki efek jika Anda memanggilnya saat me-*render* komponen atau dalam konteks asinkronisasi yang berasal dari *rendering* komponen. Pemanggilan lainnya akan diabaikan.
```

2024-07-20 10:06 UTC, r17x commented on src/content/reference/react-dom/prefetchDNS.md
> +* Di browser, Anda dapat memanggil `prefetchDNS` dalam situasi apa pun: saat merender komponen, di Effect, di event handler, dan sebagainya.
```suggestion
* Di browser, Anda dapat memanggil `prefetchDNS` dalam situasi apa pun: saat me-*render* komponen, di Effect, di *event handler*, dan sebagainya.
```

2024-07-20 12:13 UTC, r17x approved these changes

2024-07-31 04:36 UTC, r17x requested changes

2024-07-31 04:36 UTC, r17x commented on src/content/reference/react-dom/prefetchDNS.md
> +### Melakukan prefetching DNS saat merender {/*prefetching-dns-when-rendering*/}
Minor `merender` -> `me-render`

2024-07-31 05:10 UTC, andriawan commented on src/content/reference/react-dom/prefetchDNS.md
> +### Melakukan prefetching DNS saat merender {/*prefetching-dns-when-rendering*/}
done

2024-07-31 07:23 UTC, r17x approved these changes

2024-08-15 09:02 UTC, resir014 approved these changes

2024-08-15 09:02 UTC, merged